### ISSUE TITLE
piping to tee masks ember build errors

### ISSUE THREAD

**Issue by lachie** [thoughtbot/ember-cli-rails#106]
Hey
`ember-cli-rails` runs the ember build command like: 
```
/rails_app/node_modules/.bin/ember build  --environment development --output-path /rails_app/tmp/ember-cli-deadbeef/apps/myapp | /usr/bin/tee -a /rails_app/log/ember-myapp.development.log
```

Due to how shell pipelines work, the return code for that is always `0` (as long as `tee` has no problems).

This is masking the unrelated problem I'm having with `ember build` (`install_dependencies` isn't installing bower components).

Normally how I'd fix this is to use bash and turn on the pipefail option. However this would mean the gem would have a dependency on bash which probably isn't such a great idea.

I've forked the gem and I'm going to remove the log redirection & silencing stuff.

I'll possibly look at controlling the log output using IO.popen, but I'm not really sure that it makes sense for a gem like this. The reason I say this is that the normal asset compile stuff just logs to the console and moves on, it doesn't generally write to any log on disk.

**Comment by rondale-sc** [comment]
@lachie We spent quite some time trying to figure out how to properly log each app and still have both streams go to stdout (it is still very much a work in progress).  

We were endeavoring to not have Bash deps.  If you find some way to do this I'd definitely think this'd be a good addition.

**Comment by lachie** [comment]
For the record, here are the changes on my branch: https://github.com/blake-education/ember-cli-rails/blob/feature/various-fixes/lib/ember-cli/app.rb
I realise you won't want to merge this, but I'm pretty happy not to worry about the logs.

Here's how I imagine the in-ruby log teeing might look (untested):
```
    def silence_build(&block)
      old_silent,@silenced = @silenced,true
      yield
    ensure
      @silenced = old_silent
    end

    def silenced?
      !! @silenced
    end

    def in_app_path(&blk)
      Dir.chdir(app_path, &blk)
    end

    # need to open/close log_io somewhere else
    def output_ios
      if silenced?
        [ log_io ]
      else
        [ $stdout, log_io ]
      end
    end

    def system(cmd, options={})
      ios = output_ios
      in_app_path do
        IO.popen(env_hash, cmd, 'r', err: :out) do |io|
          if line = io.gets
            ios.each {|io| 
              io.puts line
              io.flush
            }
          end
        end
      end
    end

    def system!(cmd, options={})
      system(cmd, options) || raise("command failed cmd=#{cmd}, exit=(#{$?})")
    end

    def spawn(cmd, options={})
      in_app_path do
        Kernel.spawn(env_hash, cmd, err: :out)
      end
    end
```

**Comment by rondale-sc** [comment]
@lachie I'll try this out sometime and let you know what I think. :)

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

@rondale-sc please let us know if you've made any progress. @lachie if you still feel strongly about your solution, please open a PR.

Thanks for your patience.
