### ISSUE TITLE
When ember command fails in development restart it.

### ISSUE THREAD

**Issue by rondale-sc** [thoughtbot/ember-cli-rails#107]
I believe that if add a check to interrogate whether the process is still alive [here](https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/middleware.rb#L21) (by checking to see if the `@pid`  is still alive) we can retrigger the command or at least report it to the user.

Thoughts?

**Comment by rwz** [comment]
Yeah, this is super frustrating. Will probably look into that this Friday. Totally :+1: this feature.

**Comment by rwz** [comment]
@rondale-sc Added a branch called `runner` that should take care of this issue. Give it a try and report issues :)

**Comment by rondale-sc** [comment]
Will do

**Comment by seanpdoyle** [comment]
@rwz @rondale-sc I think this is closed by #145. Please let me know if you disagree and I'll reopen.
