### ISSUE TITLE
adding application js/css to test html

### ISSUE THREAD

**Issue by danielspaniel** [thoughtbot/ember-cli-rails#133]
You have a nice setup for excluding certain assets ( using exclude_ember_deps flag ) that are compiled by sprockets and dumped into the  rails application.js file:

```ruby
EmberCLI.configure do |c|
  c.build_timeout = 15 # in seconds
  c.app :frontend, exclude_ember_deps: "jquery"
end
```

But then when the tests run, they need the application.js file ( because that is where jquery is ) just like the main ember app does.  We typically include this ( application.js file ) in the our rails html file where we are including the ember assets. 

Anyway .. I am doing this to override the EmberTestsController, to include the applicatoin.js/css in the test html file. 

```ruby
require 'ember_tests_controller'

class EmberTestsController
  def index
    html = test_html_with_corrected_asset_urls
    add_rails_files html
    render text: html, layout: false
  end

  def add_rails_files(html)
    idx = html.index("<base href=\"/\" />")
    html.insert(idx, "<script src=\"/assets/application.js\"></script><link rel=\"stylesheet\" href=\"/assets/application.css\">")
  end
end
```

Wonder if you want me to do a PR to include this as optional flag for test mode? or just default behavior. I think it should be default behavior myself.

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

You mentioned opening a PR. If you still feel strongly about your solution, please do so.

Thanks for your patience.
