### ISSUE TITLE
javascript errors from rails javascript_include_tag 'application' swallowed by ember

### ISSUE THREAD

**Issue by Leooo** [thoughtbot/ember-cli-rails#146]
Hello, I'm not sure this is the right way to do it, but to smooth the transition from the asset pipeline to ember-cli I am right now juxtaposing my old js files from rails, with the ones of ember-cli (in a separate root folder frontend/).

So in my rails layout application.html.haml I have something like:

```
    - if use_ember?
      = javascript_include_tag "ember-init/assets"
      = include_ember_script_tags :frontend
    - else
      = javascript_include_tag "notember/notember"
    = javascript_include_tag "application"
```

My problem is: normal javascript errors in app/assets/javascript/application.js are not logged to the console anymore. Would you see of any possible trick to make them reappear? Right now I'm already using the following lines to log my Ember errors (desactivating those lines doesn't help to show js errors of the asset pipeline).

```
//in app.js
Ember.RSVP.on('error', function(error) {
  log(error,"red");
  Ember.Logger.assert(false, error);
});

Ember.onerror = function(error) {
  error_handling(error.message,"","",error.stack);
  return true;
};

window.onerror = function (msg, url, line,col,error) {//https://bugsnag.com/blog/js-stacktraces/
  var stack=(typeof error==="undefined" ? "" : error.stack);
  error_handling(msg,url,line,stack);
  if(!Ember.isNone(console)) {console.trace();}
  return true;
};

function error_handling(msg,url,line,stack) {...}
```

When I say 'errors swallowed', I mean not logged in the console. Maybe I could see them by opting in for 'debug all errors', but unfortunately I have to leave the "script" tab disabled in Firebug or my app gets regularly crashed.

Many thanks

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.
