### ISSUE TITLE
Avoid adding acronyms to ActiveSupport::Inflector

### ISSUE THREAD

**Issue by CloCkWeRX** [thoughtbot/ember-cli-rails#151]
Due to https://github.com/rails/rails/issues/17879 and https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/engine.rb#L5 we started seeing addresses in our system render as

```
123 Example Street, North CLI Ffe WA
```
Instead of
```
123 Example Street, NORTHCLIFFE WA
```
... when we used .titleize or similar.

The fact that ember CLI rails had defined something that changes global state in this way entirely non-intuitive; at least when you expect this to be a self contained library. This should be something that users of the gem opt into; or contained to only the code that requires it - IE; introducing a wrapper function that is aware of the few places this is needed would be a better approach.

**Comment by seanpdoyle** [comment]
This behavior and global state leakage is unacceptable. We'll look into this.

Thank you for bringing this to our attention.

**Comment by seanpdoyle** [comment]
@CloCkWeRX would you mind verifying a potential fix for this issue?

Please update your `Gemfile`:

```rb
# Gemfile
gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails", branch: "sd-remove-inflection"
```

Then try to reproduce the improperly inflected title.

**Comment by seanpdoyle** [comment]
@CloCkWeRX I've merged that branch, could you retry with `master`:

```rb
# Gemfile
gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails"
```

**Comment by CloCkWeRX** [comment]
Seems happy.
