### ISSUE TITLE
EmberCLI::App#command fails if there is a space in the path

### ISSUE THREAD

**Issue by Gowiem** [thoughtbot/ember-cli-rails#156]
I saw this while spinning up a testing suite on my company's CI server. We have long ugly path names on our Jenkins box like `/var/lib/jenkins/jobs/UXF-Services CI Pull Requests/workspace` which were causing issues like this error:
```
sh: /var/lib/jenkins/jobs/UXF-Services: Permission denied
/usr/bin/tee: Requests/workspace/log/ember-frontend.development.log: No such file or directory
```

Digging through the code a tiny bit it would make sense if the paths that come out of PathSet are escaped for spaces or any other characters that would mess with a shell command.

If I have time I'll try to throw something together for this.

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.

**Comment by neilthawani** [comment]
I am experiencing this issue currently in /Google Drive/rails_root.

**Comment by seanpdoyle** [comment]
@Gowiem @neilthawani would you mind pulling down the latest 

https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.5.4

and trying again?
