### ISSUE TITLE
ember cli only buildable in production or development environment

### ISSUE THREAD

**Issue by jpaas** [thoughtbot/ember-cli-rails#158]
I was trying to use the new config.ember_cli_rails_mode option, but I couldn't get it working. Finally I discovered that the ember command is only ever run with either the development or production environment. See https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb#L212

Should it not use ember_cli_rails_mode?

I'm trying to use my rails app to test my multiple ember app web clients which means I need to mount them all different locations. In production they all run from the root of the server. So in my rails environment I need a different baseURL. I've create a new environment called 'rails' but I can't use it.

Surely other people must have the same issue in staging environments for example?

**Comment by timrwilliams** [comment]
Did you ever resolve this? I think I'm facing the same issue deploying to a **staging** Rails environment on Heroku. My vendor.js is compiled correctly as part of the push but when I first hit a page on the app the ember build server is kicking in and throwing errors.

**Comment by timrwilliams** [comment]
Ignore me, I upgraded to the v0.3.1 and adding this to my staging.rb environment file switched ember in to production mode fine on Heroku:

    config.ember_cli_rails_mode="production"

**Comment by jpaas** [comment]
I was never able to get ember_cli_rails to work properly for me and I ended up abandoning it. I was trying to use it to run acceptance tests for a family of ember apps that use the rails server for web services. But I could never get it to mount multiple ember apps with the right environment.

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.
