### ISSUE TITLE
Doesn't work without consider_all_requests_local = true

### ISSUE THREAD

**Issue by jaurand** [thoughtbot/ember-cli-rails#161]
We need this flag set to false in production.  I tried setting the config.use_ember_middleware and config.use_ember_live_recompilation to true, but I'm still getting 404 errors on vender.js and app.js.  Am I missing something?  We deploy with capistrano to an Ubuntu server on AWS.  The readme has a section for deploying to Heroku, but nothing else for deployment.

**Comment by franzliedke** [comment]
I agree about the need for a section on deployment in general.

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long.

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.
