### ISSUE TITLE
Serving html before compilation is done

### ISSUE THREAD

**Issue by PatrickKing** [thoughtbot/ember-cli-rails#173]
I'm seeing rails return its response for a page before ember-cli-rails has finished compiling everything, with the result that I need to refresh the page twice to see changes. This might be related to the general slowness of builds that I'm seeing, 8 seconds for an ember app with three templates. Any idea what's up?

rails (4.2.0)
ember-cli-rails (0.3.2)
node v0.12.4
ember-cli 0.2.7

**Comment by Leooo** [comment]
+1

**Comment by Leooo** [comment]
this seems to happen only when not using guard livereload

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.
