### ISSUE TITLE
Ember app directory needed on production

### ISSUE THREAD

**Issue by franzliedke** [thoughtbot/ember-cli-rails#175]
We have a rather complicated workflow for building our Rails app. As we're currently transitioning the frontend to an Ember app, we noticed that apparently the Ember app directory needs to be present on the production server even though no files are ever served from it.

This is apparently due to the `include_ember_[script|stylesheet]_tags` helpers which check the app's `package.json` for the app's name, as that is used for the compiled JS/CSS filename.

Can we build a workaround for these kind of setups? Maybe we could use the name specified [in the initializer](https://github.com/rwz/ember-cli-rails/tree/8a03bdf639ac4677487710a48ce7b1ddb546dde3#multiple-embercli-apps) instead?

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.

**Comment by franzliedke** [comment]
Please reopen. I'd love to see this fixed / help in doing so.

**Comment by seanpdoyle** [comment]
There's been a lot of movement on this repo recently.

Could you try out version [0.5.3](https://rubygems.org/gems/ember-cli-rails/versions/0.5.3) and verify that you're still having the same issues.

**Comment by seanpdoyle** [comment]
Closing due to the new direction the project has taken:

https://github.com/thoughtbot/ember-cli-rails/issues/165#issuecomment-157912966

Thanks for opening up this issue! Hopefully some of the changes we've been making will help you resolve your issues.
