### ISSUE TITLE
instructions on precompile assets with nginx + puma

### ISSUE THREAD

**Issue by mehulkar** [thoughtbot/ember-cli-rails#178]
I'm attempting to deploy on a machine with Nginx and Puma and for the life of me can't figure out how to precompile. The digests from `rake assets:precompile` seem to be wrong. I've tried messing around with nginx configs, but requests seem to be made for assets with digests that no longer exist. 

not sure what i'm doing wrong.

**Comment by seanpdoyle** [comment]
@mehulkar thanks for bringing this to our attention.

Would you mind providing some code snippets / example code / more context around the issue?

**Comment by mehulkar** [comment]
going to close this. No longer using ember-cli-rails and don't have a handy project to reproduce. Ended up putting my ember-cli project as a subdirectory inside the Rails directory and running separate processes. An extra terminal tab isn't really that painful :)

**Comment by seanpdoyle** [comment]
@mehulkar thanks for bringing this to our attention.

We're trying to address problems like this with https://github.com/thoughtbot/ember-cli-rails/pull/250.

Once that lands, I'd encourage you to try the project out again if you'd like.
