### ISSUE TITLE
Exclude_ember_deps option not working for Ember 1.13 / Ember cli 0.2.7 application

### ISSUE THREAD

**Issue by emeryamiller** [thoughtbot/ember-cli-rails#179]
I'm attempting to migrate an Ember 1.9 app to 1.13.  I chose to simply update ember cli, create a new app, update ember from 1.12 -> 1.13 and ember data to 1.13, and then start copying and pasting the code over to this new app.  I'm using ember cli rails to link this app to my rails app.

When I add it like this:
```c.app :checkout2, path: '../checkout'```

it works fine, but includes jquery 1.11.3.  Since my app already includes jquery, I tried adding the exclude_ember_deps option (this used to work for the Ember 1.9 app):

```c.app :checkout2, path: '../checkout', exclude_ember_deps: 'jquery'```

But now, with this change, it fails giving the following error in the browser:

```Uncaught Error: Could not find module jquery```

Not sure what to look for next to debug this.

**Comment by seanpdoyle** [comment]
@emeryamiller  Hey there, sorry this has gone silent.

There's been a lot of movement on this repo recently.

Could you try this again for version [0.5.3](https://rubygems.org/gems/ember-cli-rails/versions/0.5.3)?

We hope your upgrade from `ember-cli@0.2.7` went well!

Unfortunately, we're no longer supporting `ember-cli` versions `<= 1.13.x`, so we'll have to close this issue.
