### ISSUE TITLE
Source Map Comments?

### ISSUE THREAD

**Issue by imackinn** [thoughtbot/ember-cli-rails#200]
Is there anyway to maintain a fingerprinted source map comment from ember-cli? ie. `//# sourceMappingURL=vendor-266f0c0df67fcb9cb0e59bf7beacecf6.map` at the bottom of a JS file? 

Fingerprinting seems to be hard coded to off for ember-cli-rails, but I'm not sure how to maintain the map comment.

**Comment by seanpdoyle** [comment]
@imackinn this should have been resolved by https://github.com/thoughtbot/ember-cli-rails/commit/bb4b03c58e4387a7914b3b509d689b07f8a9c923.

Could you try `master`:

```rb
# Gemfile

gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails"
```

**Comment by seanpdoyle** [comment]
Closing this issue.

If you're able to reproduce with `master`, please ping me here and I'll re-open.

**Comment by seanpdoyle** [comment]
@imackinn on further thought, this will take more than just the `master` branch of the gem.

Please read and follow https://github.com/thoughtbot/ember-cli-rails/issues/30#issuecomment-154768936, posting back here with your results
