### ISSUE TITLE
Boot earlier to have the benefits of sping

### ISSUE THREAD

**Issue by GCorbel** [thoughtbot/ember-cli-rails#203]
Hi,

I'm using EmberCli-Rails with capybara-webkit and spring. It works but Ember takes approximatively 12 seconds to boot. It's not huge but I need to run it frequently. I think if we boot Ember ealier and keep it alive with spring, it can increase the productivity.

I tried to do this code :  

    EmberCLI.configure do |c|
      c.app :frontend, path: '../frontend', build_timeout: 30
    end
    if EmberCLI.env.development?
      EmberCLI[:frontend].run
    else
      EmberCLI[:frontend].compile
    end

When I run my spec, it works for the first time but, the second time, I have this error : 

     Failure/Error: Unable to find matching line from backtrace
     ActionView::MissingTemplate:
       Missing template application/index with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby]}. Searched in:
         * "/api/app/views"
         * "/usr/local/bundle/gems/clearance-1.10.1/app/views"

Ember seems to not be correctly booted. I think the compilation is kept somewhere but I don't know how to do to use it.

It's the same think when I use `run`. I can see the process ids still the same between the calls.

Do you have a clue? What you think?

Thanks!

**Comment by GCorbel** [comment]
I worked on a solution.

    --- a/lib/ember-cli-rails.rb
    +++ b/lib/ember-cli-rails.rb
    @@ -79,7 +79,8 @@ module EmberCLI
       end

       def cleanup
    -    root.rmtree if root.exist?
    +    # TODO : delete all except the one with the same uid in test
    +    root.rmtree if root.exist? && !EmberCLI.env.test?
       end

       def each_app
    diff --git a/lib/ember-cli/app.rb b/lib/ember-cli/app.rb
    index fb31cc4..720c682 100644
    --- a/lib/ember-cli/app.rb
    +++ b/lib/ember-cli/app.rb
    @@ -34,8 +34,14 @@ module EmberCLI
           prepare
           FileUtils.touch lockfile_path
           cmd = command(watch: true)
    -      @pid = exec(cmd, method: :spawn)
    +      if EmberCLI.env.test?
    +        silence_build { @pid = exec(cmd, method: :spawn) }
    +      else
    +        @pid = exec(cmd, method: :spawn)
    +      end
           Process.detach pid
    +      p Spring::SID.pgid
    +      p Process.getpgid(pid)
           set_on_exit_callback
         end

    diff --git a/lib/ember-cli/runner.rb b/lib/ember-cli/runner.rb
    index a6cf0f5..daad3e5 100644
    --- a/lib/ember-cli/runner.rb
    +++ b/lib/ember-cli/runner.rb
    @@ -11,7 +11,7 @@ module EmberCLI
         def process
           return if skip?

    -      if EmberCLI.env.development?
    +      if EmberCLI.env.development? || EmberCLI.env.test?
             start_or_restart!
           else
             compile!

It seems to be easy to do but it's hard work to find. It works except when I stop spring, the process continue to run. I have to find a way to kill it. With `Spring::SID.sid` I can have the process used by spring. I have to find a way to kill the EmberCli process when Spring is stopped.

**Comment by seanpdoyle** [comment]
Thanks for bringing this to our attention @GCorbel.

How is this going? Were you able to turn your findings in https://github.com/thoughtbot/ember-cli-rails/issues/203#issuecomment-134961734 into workable code?

If so, would you mind opening a pull request containing the changes in that diff?

I'm going to close this issue, and look forward to your PR.
