### ISSUE TITLE
Reloading the page does not work

### ISSUE THREAD

**Issue by philpee2** [thoughtbot/ember-cli-rails#205]
I can visit `http://localhost:3000/#/posts`, and that works fine, and changes the URL to `http://localhost:3000/posts`. However, if I then reload the page, I get a Rails routing error `No route matches [GET] "/posts"`. To reload the page, I have to manually add `#/` back to the URL.

**Comment by supairish** [comment]
This is a question better asked on Stackoverflow.  But basically you need a catch all route that goes to the controller#action that renders the page with ember on it.

**Comment by philpee2** [comment]
Adding `get '*path' => 'application#index'` to `routes.rb` worked. Thanks!

**Comment by seanpdoyle** [comment]
Thanks for helping out, @supairish.

@philpee2 closing this issue. If you're still having trouble, please ping me and I'll reopen.
