### ISSUE TITLE
npm install --save-dev ember-cli-rails-addon@0.0.12

### ISSUE THREAD

**Issue by kgish** [thoughtbot/ember-cli-rails#206]
Since a newer version of `ember-cli-rails-addon` has been released, the `README.md` documentation needs to be updated to:
```
npm install --save-dev ember-cli-rails-addon@0.0.12
```

**Comment by seanpdoyle** [comment]
Thanks for bringing this to our attention. This change was made in https://github.com/thoughtbot/ember-cli-rails/commit/6df3a10be3d8328a89a92c3a01241be359a6861f, and has been merged into master.

**Comment by kgish** [comment]
Cool!
