### ISSUE TITLE
Problems using bootstrap

### ISSUE THREAD

**Issue by kgish** [thoughtbot/ember-cli-rails#207]
In my `ember-cli-build.js` I use `app.import` to include bootstrap like this:
```
app.import('bower_components/bootstrap/dist/css/bootstrap.css');
app.import('bower_components/bootstrap/dist/css/bootstrap.css.map', { destDir: 'assets' });
app.import('bower_components/bootstrap/dist/js/bootstrap.js');
```
However, I'm getting the following error:

![screenshot](https://cloud.githubusercontent.com/assets/79195/9831412/11863e06-5957-11e5-9d3e-cdcc07d5eb27.png)

Is there something I am forgetting to do with the asset pipeline in order to enable this through `ember-cli-rails`?

**Comment by kgish** [comment]
Never mind, I found the problem.

For some weird reason I had the following lines at the top of my `app/styles/app.css` file:
```
/*
 *= require bootstrap/dist/css/bootstrap.min.css
 *= require_self
 */
```
I removed these lines and the problem has gone away.

**Comment by seanpdoyle** [comment]
Thanks for getting to the bottom of this.

I'm going to close this issue. If it's still a problem, please let us know and we'll reopen.

**Comment by kgish** [comment]
Thanks!
