### ISSUE TITLE
ember init doesn't create files in current directory

### ISSUE THREAD

**Issue by xijo** [thoughtbot/ember-cli-rails#209]
Hello everyone,

I was following the instructions from README.md, but I experience a strange behavior. 

```
$ mkdir frontend
$ cd frontend
$ ember init
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
installing app
  identical .bowerrc
  identical .editorconfig
  identical .ember-cli
  identical .jshintrc
  identical .travis.yml
  identical .watchmanconfig
  identical README.md
  identical app/app.js
  identical app/index.html
  identical app/router.js
  identical app/templates/application.hbs
  identical bower.json
  identical config/environment.js
  identical ember-cli-build.js
  identical .gitignore
  identical package.json
  identical public/crossdomain.xml
  identical public/robots.txt
  identical testem.json
  identical tests/.jshintrc
  identical tests/helpers/resolver.js
  identical tests/helpers/start-app.js
  identical tests/index.html
  identical tests/test-helper.js
Installed packages for tooling via npm.
Installed browser packages via Bower.

# but
$ ls -la
total 0
drwxr-xr-x   2 owner  group   68 Sep 13 09:43 .
drwxr-xr-x  25 owner  group  850 Sep 13 09:43 ..
```

So ember cli finds those files *somewhere* but I cannot see anything inside of the directory where the initialisation should take place. Any ideas to find the problem? 

These are my versions:

```
$ ember --version
version: 1.13.8
node: 0.12.0
npm: 2.13.4
os: darwin x64
```

**Comment by mikekellyio** [comment]
I ran into this. The problem was that somewhere in a directory above there was a ``package.json`` that ``ember`` found and tried to use instead.

**Comment by seanpdoyle** [comment]
Thanks for opening this issue and bringing this to our attention.

Unfortunately, this doesn't sound like an `ember-cli-rails` issue, since `ember-cli-rails` and `ember-cli` are separate projects.

I'm going to close this issue. I suggest that you [open an issue on the ember-cli project](https://github.com/ember-cli/ember-cli/issues).

If you still believe that this is an `ember-cli-rails` problem, feel free to comment and I'll re open the issue.
