### ISSUE TITLE
Running acceptance test from ember

### ISSUE THREAD

**Issue by benoittgt** [thoughtbot/ember-cli-rails#213]
Hello

I'm trying to run the test from ember. Like this one : 
```javascript
test('with 25 users', function(assert) {
  visit('front/stores/5282/users');

  andThen(function() {
    assert.equal(find('label').length, 25);
  });
});
```

But when I visit the qunit page : `XMLHttpRequest cannot load http://www.exemple.me:3000/api/v1/5282/users. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:7357' is therefore not allowed access.`

I should have the crsf token inside my index page in `emberapp/tests/index.html`but I should I know it? :/

I've tried the advices given in the readme with the mount point like this one without success: 
```ruby
  namespace :front do
    get '/', to: 'front#index'
    mount EmberCLI::Engine => "ember-tests" if Rails.env.development?
    get '/*other', to: 'front#index'
  end
```

Thanks for your help.

**Comment by seanpdoyle** [comment]
I'm sorry @benoittgt but this doesn't sound like an `ember-cli-rails` issue.

It looks like this has to do with the way you have your Mirage configured.

I'm closing this issue.

If you have more information about this failure please share it.
