### ISSUE TITLE
undefined method `include_ember_script_tags'

### ISSUE THREAD

**Issue by DrSayre** [thoughtbot/ember-cli-rails#215]
I keep getting this error when I try to access the page.  I am using the rails-api gem which I believe is causing my problems.  If it is, should I switch to the version of rails, or is there a module I can include for the helper to work with rails-api?

This is how I have my root html.erb page setup:
```
<%= include_ember_script_tags :web_portal_app %>
<%= include_ember_stylesheet_tags :web_portal_app %>
```

**Comment by seanpdoyle** [comment]
Thanks for bringing this to our attention.

`ember-cli-rails`'s tag helpers depend on Rails' view rendering ([rails/actionview](https://github.com/rails/rails/tree/master/actionview)?). 

Unfortunately, I don't have a lot of experience working with an API only build of Rails (`rails-api`, Rails 5's `--api` flag, etc). You might be able to incrementally add back the parts of the Rails view stack that you need, but I don't have any strong suggestions.

If you're planning on serving an ERB-backed HTML page that uses the `include_ember_**_tags` helpers, I suggest using the normal Rails stack.

I'm closing the issue. Please feel free to leave additional comments. We can reopen the issue if there are any breakthroughs on either side.
