### ISSUE TITLE
ember-cli-rails does not interact well with ember-cli addons that load external javascript

### ISSUE THREAD

**Issue by jeffreybiles** [thoughtbot/ember-cli-rails#220]
I've been trying to use [ember-cli-stripe](https://github.com/sweettooth/ember-cli-stripe) and/or [ember-stripe-service](https://github.com/ride/ember-stripe-service), and they both are failing when using ember-cli-rails.  They both rely on loading an external javascript library from Stripe, and both are failing for the reason that the global loaded by the library (Stripe or StripeCheckout) is not defined.  When I run the ember-cli app on its own the problem disappears, leading me to believe that the problem is with ember-cli-rails.

Thanks for making this gem!  Wish I could offer a PR to go with the issue, but I'm pretty stumped.

**Comment by seanpdoyle** [comment]
@jeffreybiles thanks for bringing this to our attention, it's on our radar and we're looking into it.

**Comment by seanpdoyle** [comment]
@jeffreybiles initial implementation in https://github.com/thoughtbot/ember-cli-rails/pull/224

**Comment by seanpdoyle** [comment]
@jeffreybiles could you give `master` a shot?

https://github.com/thoughtbot/ember-cli-rails/pull/224 should address your issues.

Also, it might be worth checking out https://github.com/thoughtbot/ember-cli-rails/pull/228

**Comment by seanpdoyle** [comment]
Give https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.4.0 a shot!

**Comment by jeffreybiles** [comment]
Thanks, this will be very useful for next iteration of the payment system.  If I had planned ahead better, I would have saved the spike that was using stripe within Ember.
