### ISSUE TITLE
undefined method `include_ember_index_html'

### ISSUE THREAD

**Issue by dchersey** [thoughtbot/ember-cli-rails#234]
I'm following the instructions in the Readme.md for setting up a clean app based on the RailsStarterKit, and I'm getting undefined method `include_ember_index_html'.

I'm rendering the ember-cli index.html into 'users#show' and my show.html.erb includes
```erb
<%= include_ember_script_tags :ui %>
<%= include_ember_stylesheet_tags :ui %>

<%= include_ember_index_html :ui %>
```

The first 2 helpers work; the 3rd is not found. I don't see it defined in ember_rails_helper.rb either. 

Has this changed? If so to what?
 I'm using ember-cli-rails (0.3.5)

Thank you!

**Comment by dchersey** [comment]
Doh!
Apparently did not get the latest release when I did gem 'ember-cli-rails'.  Specified 
```
gem "ember-cli-rails",  '0.4.1'
````

and it worked.

**Comment by seanpdoyle** [comment]
Yup! I was just going to suggest that.

It's also worth noting that 

```erb
<%= include_ember_script_tags :ui %>
<%= include_ember_stylesheet_tags :ui %>
```

Are supposed to be rendered with `render layout: true` (what controllers default to), whereas:

```erb
<%= include_ember_index_html :ui %>
```

is supposed to be rendered with `render layout: false`.

The first two are injected INTO a Rails layout/page, whereas the last one *replaces* a Rails layout/page.

If you still need markup from Rails (like `csrf_meta_tags`), you can pass `include_ember_index_html` a block that accepts `head` and `body`:

https://github.com/thoughtbot/ember-cli-rails#usage

**Comment by seanpdoyle** [comment]
Closing this issue.

**Comment by dchersey** [comment]
Thanks! That additional clarification is very helpful.
