### ISSUE TITLE
Ember-cli-rails is building ember-cli multiple times

### ISSUE THREAD

**Issue by alexanderjeurissen** [thoughtbot/ember-cli-rails#237]
I know there is already an issue for this (issue: #184) however the solutions shown in that issue as well as the updated readme don't fix the issue for me.

I serve the rails + ember-cli app using foreman, and when I save a file and thus the app rebuilds it builds twice. Also when starting foreman and navigating to a page thus triggering the ember-cli build it also builds twice on the initial build.

Here are some screenshots to illustrate the problem:

![screen shot 2015-11-03 at 15 25 44](https://cloud.githubusercontent.com/assets/1220084/10910431/a8eac990-823f-11e5-8814-bccde7058efb.png)

![screen shot 2015-11-03 at 15 27 21](https://cloud.githubusercontent.com/assets/1220084/10910430/a8e99f3e-823f-11e5-96f9-936fbb7b292f.png)

![screen shot 2015-11-03 at 15 28 44](https://cloud.githubusercontent.com/assets/1220084/10910429/a8e966fe-823f-11e5-8d26-ba6c06fd44ae.png)

This is my Puma config:
```ruby
workers Integer(ENV['PUMA_WORKERS'] || 3)
threads Integer(ENV['MIN_THREADS']  || 1), Integer(ENV['MAX_THREADS'] || 16)

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # worker specific setup
  ActiveSupport.on_load(:active_record) do
    config = ActiveRecord::Base.configurations[Rails.env] ||
      Rails.application.config.database_configuration[Rails.env]
    config['pool'] = ENV['MAX_THREADS'] || 16
    ActiveRecord::Base.establish_connection(config)
  end
end
```

If you need some additional info let me know.

**Comment by seanpdoyle** [comment]
What is your `ENV["PUMA_WORKERS"]` and `ENV["MAX_THREADS"]` set to?

According to https://github.com/thoughtbot/ember-cli-rails#serving-from-multi-process-servers-in-development, they should both be `1`.

I'm closing this. Please try with the updated `ENV` values. If this is still an issue ping me in this issue and I'll gladly reopen.

**Comment by alexanderjeurissen** [comment]
Ok seemed due to switching between branches and because the `.env` isn't version controlled indeed the ENV variables were wrong..

Live reloading works fine now and only builds once with an improvement in build time :+1: however initially when starting the server multiple builds are still showing up. This is not really an issue, just an observation. Sequential builds where the real bottleneck and that's solved now. Thx.

**Comment by seanpdoyle** [comment]
Glad we could help!
