### ISSUE TITLE
Running 'rails g ember-cli:heroku' results in error

### ISSUE THREAD

**Issue by rlpacht** [thoughtbot/ember-cli-rails#255]
I want to push an app to heroku but when I try to run that command I get this error ```Could not find generator 'ember-cli:heroku'. Maybe you meant 'ember-cli:init' or 'erb:mailer' or 'migration'
Run `rails generate --help` for more options. ```

Any suggestions for why I might be getting this error and how I might fix it?

**Comment by seanpdoyle** [comment]
@rlpacht that looks like you're running an older version of `ember-cli-rails`.

The Heroku generator was introduced in [0.4.0](https://github.com/thoughtbot/ember-cli-rails/blob/master/CHANGELOG.md#040).

I suggest updating `ember-cli-rails` to `0.4.3` and trying again.

**Comment by seanpdoyle** [comment]
I'm closing this. Please feel free to comment back about your results. 

If you're still having issues I'll gladly reopen.

**Comment by ACPK** [comment]
@seanpdoyle - I also get this issue and am using "ember-cli-rails" version 0.6.1.

**Comment by seanpdoyle** [comment]
@ACPK Are you running `rails g ember:heroku` ([as described in the `0.6.1` README](https://github.com/thoughtbot/ember-cli-rails/tree/v0.6.1#heroku))?
