### ISSUE TITLE
gem version does not match ember-cli addon version?

### ISSUE THREAD

**Issue by dchersey** [thoughtbot/ember-cli-rails#280]
Hi, I was going through the instructions in the readme, and it says to 

```
Be sure that the addon's MAJOR and MINOR version matches the gem's MAJOR and MINOR versions.

For instance, if you're using the 0.5.x version of the gem, specify ~> 0.5.0 ion in your Ember app's package.json.
```

This is confusing, because the latest version of the gem appears to be 0.4.3 and the latest addon seems to be     "ember-cli-rails-addon": "0.0.13",

Am I missing/misreading something? Will these work together?

**Comment by seanpdoyle** [comment]
@dchersey you were absolutely correct to expect that a `0.5.x` version of the gem and addon would exist.

Unfortunately, the `0.5.x` version are not yet published. 

Expect releases in the next few days.

Very sorry for the confusion, but the README is ambitiously ahead of reality.

**Comment by seanpdoyle** [comment]
@dchersey scratch all that, I've released them both:

* https://github.com/thoughtbot/ember-cli-rails/commit/1c87745ce02346784b440dcb93401cd14c3fac3e
* https://github.com/rondale-sc/ember-cli-rails-addon/commit/a94f6eaa72a372e1cae40189cd31275fe88ebdd6

**Comment by dchersey** [comment]
sweet, thanks!
