### ISSUE TITLE
`include_ember_script_tags` resulting in 404s

### ISSUE THREAD

**Issue by botandrose** [thoughtbot/ember-cli-rails#292]
Heya heya, thanks for Ember-CLI-Rails! Really nice to see Thoughtbot putting some manpower into this gem.

Anywho, just upgraded from 0.4.3 to 0.5.4, and `include_ember_script_tags(:exam_builder)` is resulting in 404s:
```
/javascripts/exam_builder/assets/vendor.js
/javascripts/exam_builder/assets/exam-builder.js
```

I'm running latest everything, except Sprockets `~> 2.0` because of Compass. Any ideas, or should I attempt to chop this down into a minimal repro?

**Comment by seanpdoyle** [comment]
@botandrose this appears to be the same issue as https://github.com/thoughtbot/ember-cli-rails/issues/186

If you could prove a minimal repo for me to help debug, that would be great.

Before doing so:

* Are you on the latest [ember-cli-rails-addon](https://github.com/rondale-sc/ember-cli-rails-addon/)?
* Are you running on a [multi-threaded server with more than 1 worker](https://github.com/thoughtbot/ember-cli-rails#serving-from-multi-process-servers-in-development)?
* Are you [raising on missing assets](https://github.com/thoughtbot/ember-cli-rails/blob/98919d25f777d9fb3c6f72a9cb3ab3f2724fe2f8/spec/dummy/application.rb#L29)?

**Comment by botandrose** [comment]
Can do!

To answer your questions, yes, no, and yes.

**Comment by botandrose** [comment]
@seanpdoyle Here you go: https://github.com/botandrose/ember_cli_rails_bug_repro

Let me know if there's anything I can do to help!

**Comment by seanpdoyle** [comment]
@botandrose it looks like some misconfiguration is to blame for your issues:

https://github.com/botandrose/ember_cli_rails_bug_repro/pull/1

It's also worth noting that moving forward, I **strongly** recommend you migrate away from including the script / style tags.

`render_ember_app` (which renders the EmberCLI generated `index.html`) is the future of this project. If you can avoid routing to your `ApplicationController`, I'd recommend using the `ember-cli-rails`-generated controller.

https://github.com/thoughtbot/ember-cli-rails#usage

**Comment by botandrose** [comment]
@seanpdoyle Thanks very much for your time on this, and on a Saturday!

`render_ember_app` seems like the logical step forward if your app is a SPA. Unfortunately, mine is not. We actually have multiple ember apps that are effectively extremely complicated widgets, embedded in a large page that is otherwise rendered in Rails. There also may be more than one instance of a single app embedded on a page at a given time. This isn't the typical use-case for Ember, but it is supported by them (I occasionally discover bugs in Ember related to this use-case, and they are promptly fixed by the core-team). Moving forward, will there be a supported path for this use-case and Ember-CLI-Rails, do you think?

I will examine the repro repo, now, for greater insight. Thanks again!

**Comment by seanpdoyle** [comment]
@botandrose I'm unsure about full-fledged support for this use case.

As a quick fix, you can call `EmberCli[:exam_builder].build` in a `before_action` hook in your controller.

That's a private API, but you can use it until we can come up with a better approach.

**Comment by botandrose** [comment]
Ok, that's great for now! I am happy simply to not be stuck on 0.4, for the time being. I'll give it a shot. Quick question: is that `build` method cheap if the ember app hasn't changed since last time it was invoked?

**Comment by seanpdoyle** [comment]
Yup:

https://github.com/thoughtbot/ember-cli-rails/blob/master/lib/ember_cli/app.rb#L37-L45
