### ISSUE TITLE
Rails 3.2.* compatibility looks broken

### ISSUE THREAD

**Issue by flexoid** [thoughtbot/ember-cli-rails#302]
Hi.
Looks like ```before_action``` from ```lib/ember_cli/controller_extension.rb``` breaks compatibility with Rails v3.2.*, which is supported according to the README. So, maybe you consider adding some workaround like ```respond_to?(:before_action)``` with fallback to ```before_filter``` for the period that you going to support rails 3?
Thanks

**Comment by seanpdoyle** [comment]
@flexoid thanks for bringing this issue to our attention.

This will be handled in https://github.com/thoughtbot/ember-cli-rails/pull/306.

**Comment by seanpdoyle** [comment]
@flexoid this was fixed in https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.5.6

Please try that out and let me know if you're still having issues
