### ISSUE TITLE
0.5 requires `bower_path` to be absolute

### ISSUE THREAD

**Issue by botandrose** [thoughtbot/ember-cli-rails#303]
So, I like to specify the bower dependency in `package.json`, and then symlink the binary from `node_modules/.bin/bower` to `bin/bower`. A little off the beaten path, but IMO its saner than npm's "just globally install every package if you want to use its binaries" strategy!

In any event, EmberCLI-Rails 0.4 allowed me to specify my `bower_path` as `bin/bower`, and all was well. However, after the upgrade to 0.5.4, EmberCLI-Rails looks for bower in the Ember app directory<sup>1</sup>, and then again later in the Rails root directory<sup>2</sup>, so I can't specify a relative path in the EmberCLI-Rails config anymore.

Obviously, its not a huge deal, e.g. `bower_path: Rails.root.join("exam_builder/bin/bower")` works well enough, but it is a regression from 0.4, so I thought I'd mention it. I imagine a solution would be to invoke the `Pathname(path).executable?` check within the context of the Ember app dir, rather than the Rails root dir. If this sounds acceptable, let me know and I can put together a PR.

1. https://github.com/thoughtbot/ember-cli-rails/blob/98919d25f777d9fb3c6f72a9cb3ab3f2724fe2f8/lib/ember_cli/shell.rb#L58
2. https://github.com/thoughtbot/ember-cli-rails/blob/98919d25f777d9fb3c6f72a9cb3ab3f2724fe2f8/lib/ember_cli/path_set.rb#L93

**Comment by botandrose** [comment]
Ah, just noticed that there is a 0.5.5 out that touches how executables are invoked. Will upgrade and check to see if this is still an issue.

**Comment by botandrose** [comment]
Confirmed regression still exists in 0.5.5.

**Comment by seanpdoyle** [comment]
@botandrose thanks for opening this issue!

I appreciate your desire for a custom `bower_path` configuration value, and I recognize that the behavior has changed in a non-backwards compatible way.

It is my preference that the gem expect absolute paths. Like you mentioned, `bower_path: Rails.root.join("exam_builder/bin/bower")` is a reasonable thing to do.

If you feel strongly that this isn't a good idea, I'll gladly look over your proposed PR.

If we end up rejecting that PR, I'd also love to see a PR that documents your use case and explains how to achieve it.

I'm closing this for now as a "wontfix", with any future discussion happening in your PR.

**Comment by botandrose** [comment]
@seanpdoyle if you've concluded that the paths should be absolute, then that's fine with me. :+1:

Thanks for the consideration.
