### ISSUE TITLE
error deploying via capistrano

### ISSUE THREAD

**Issue by dchersey** [thoughtbot/ember-cli-rails#319]
Hi again -- I've just built a new Ubuntu 14 server and am getting an error from ember-cli-rails when deploying via capistrano. 

```
DEBUG [23492c3d] Command: cd /var/www/releases/20151202203519 && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 NODE_VERSION=v4.2.1 RAILS_ENV=production RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 ~/.rbenv/bin/rbenv exec bundle exec rake assets:precompile )
DEBUG [23492c3d] 	rake aborted!
DEBUG [23492c3d] 	TypeError: no implicit conversion of nil into String
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/path_set.rb:83:in `initialize'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/path_set.rb:83:in `Pathname'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/path_set.rb:83:in `block in bower'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/path_set.rb:82:in `tap'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/path_set.rb:82:in `bower'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/shell.rb:40:in `install'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/app.rb:52:in `install_dependencies'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember-cli-rails.rb:84:in `block in each_app'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember-cli-rails.rb:84:in `each'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember-cli-rails.rb:84:in `each_app'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember-cli-rails.rb:42:in `install_dependencies!'
DEBUG [23492c3d] 	/var/www/shared/bundle/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01/lib/tasks/ember-cli.rake:14:in `block (2 levels) in <top (required)>'
DEBUG [23492c3d] 	Tasks: TOP => assets:precompile => ember:compile => ember:install
DEBUG [23492c3d] 	(See full trace by running task with --trace)
```

Looking at the code, I see ember-cli-rails is looking for bower_path from app_options but it's not clear where/if there is something I need to configure there. 

I updated my gem to pull from master and the error remains as above.
```
bundle show ember-cli-rails
/Users/david/projects/ia/vendor/ruby/2.2.0/bundler/gems/ember-cli-rails-7badc2581e01
```

I have also ensured my package.json includes 
```
  "devDependencies": {
    "bower": "*"
}
```
as its first dependency.

**Comment by seanpdoyle** [comment]
@dchersey thanks for opening this issue!

It's great that your root level `package.json` lists `bower` as a dependency. We depend on [Heroku's Node buildpack](https://github.com/heroku/heroku-buildpack-nodejs) to see that and install the dependencies.

Does your capistrano task have a matching step to install root-level npm dependencies?

**Comment by dchersey** [comment]
I am doing an npm install via capistrano-npm; is that what you mean?

**Comment by dchersey** [comment]
I am doing an npm install via capistrano-npm; is that what you mean?

Here's the relevant section of my capistrano script:

```ruby
set :bundle_without, %w{development test}.join(' ')
set :bundle_flags, '--local --deployment --quiet'  

set :nvm_type, :user # or :system, depends on your nvm setup
set :nvm_node, 'v4.2.1'
set :nvm_map_bins, %w{node npm}
set :nvm_node_path, '/home/adz/.nvm/versions/node/v4.2.1'
set :bower_target_path, -> { release_path.join('ui') }
set :bower_bin, '/home/adz/.nvm/versions/node/v4.2.1/bin/bower'
set :bower_flags, ''
set :npm_target_path, -> { release_path.join('ui') }
set :npm_flags, '--no-spin'
```

I am using the following capistrano gems:

```ruby
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-service'
  gem 'capistrano-nvm'
  gem 'capistrano-npm'
  gem 'capistrano-bower'
```
The log output shows that it runs npm and bower installs successfully before invoking `rake:assets:precompile`.  I tried removing the nvm, npm and bower capistrano gems and still had the same issue, except that ember-cli-rails was invoking npm using the system node.js not the one I wanted to use (4.2.1).

**Comment by seanpdoyle** [comment]
Unfortunately, I don't have much capistrano experience (and exactly 0 EmberCLI-Rails capistrano experience), so most of this is speculative.

[This code](https://github.com/thoughtbot/ember-cli-rails/blob/7badc2581e0158bb8017cf5a24a39ea8d50b77df/lib/ember_cli/helpers.rb#L5-L16) is responsible for determining if a command (the `bower` executable, in this case) is available. I didn't author that code, so I'm pretty unfamiliar with how it determines which `bower` command, if any, to use.

My suggestion is to ensure that `bower` is installed *somewhere on your $PATH*. Outside of that, I'm not sure.

**Comment by kayakyakr** [comment]
Why not hook into the npm install process like:

```JSON
"scripts": {
  "postinstall": "./node_modules/bower/bin/bower install"
}
```

Don't have to even worry about what ember-cli-rails is doing that way?

**Comment by dchersey** [comment]
I believe ember-cli does this on it's own. I already do bower install before the rails assets:precompile, which is hooked by ember-cli to do it's own compile. That step seems to involve ANOTHER bower install, and ember-cli can't find bower.   

I'm playing with this today; should have an update.

**Comment by dchersey** [comment]
Ok, it was a path issue. Adding 
```ruby
set :default_env, {
  'PATH' => '$PATH:/home/deploy/.nvm/versions/node/v4.2.1/bin'
}
```
to my production.rb in capistrano solved it.  

Thanks for your help!

**Comment by seanpdoyle** [comment]
That's great news @dchersey !

Would you mind opening a PR against the README with your findings?

Closing this for now.

**Comment by kayakyakr** [comment]
I just wanted to add, I found a slightly different solution using the capistrano-nvm gem:

```Ruby
# /config/deploy.rb
set :nvm_type, :user
set :nvm_node, 'v5.2.0'
set :nvm_map_bins, %w{node npm rake}
```

The key is the :nvm_map_bins which run on rake. This ensures the nvm environment is run for the precompile assets which is a rake task. I've also got bower as an npm dependency, so I'm running that with:

```Ruby
EmberCli.configure do |c|
  c.app :home, bower_path: Rails.root.join('home', 'node_modules', 'bower', 'bin', 'bower')
end
```

**Comment by seanpdoyle** [comment]
@kayakyakr thanks for that information!

I'm inexperienced with capistrano and ember-cli-rails. Would you mind opening a PR to the README that better explains how to set it up?
