### ISSUE TITLE
No such file or directory @ rb_sysopen - ~/project/tmp/ember-cli-HASH/apps/adminr/index.html

### ISSUE THREAD

**Issue by kozak** [thoughtbot/ember-cli-rails#321]
I've run into an issue with Ember-CLI that I have no idea how to solve. 
After installing bower with  `npm install -g bower`
and than installing momentjs and select2 via bower, the ember app stopped working with the error in the title. I've tried restarting the POW server, which usually helped with the "no such file or directory" error (I am using `export POW_WORKERS=1`).  
I've tried removing the tmp directories in adminr/tmp and rails, but it is still not working. 

The "no such file or directory" would also occur after editing a file, for example when changing a 
```coffe
App.Apple = DS.Model.extend
   name: DS.attr()
```
to the es6 coffeescript version
```coffee
`import DS from 'ember-data';`

Apple = DS.Model.extend
   name: DS.attr()

`export default Apple`
```
I usually had to restart the server. 

What could prevent ember-cli-rails from generating the index.html file? 
Thanks! 
(Stacktrace and versions below)

Stacktrace:
```
No such file or directory @ rb_sysopen - ~/project/tmp/ember-cli-9153351a-62b7-4dca-ad4b-2196997971d7/apps/adminr/index.html
```
```
1: <%= render_ember_app :adminr %>
```

```
vendor/bundle/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/sprockets.rb:19:in `read'
vendor/bundle/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/sprockets.rb:19:in `read'
vendor/bundle/bundler/gems/ember-cli-rails-7badc2581e01/lib/ember_cli/sprockets.rb:19:in `index_html'
vendor/bundle/bundler/gems/ember-cli-rails-7badc2581e01/app/helpers/ember_rails_helper.rb:19:in `render_ember_app'
```

Versions:
ember-cli: 1.13.13
ember-cli-rails-addon: "^0.5.2"
gem: (from github)
  remote: git@github.com:thoughtbot/ember-cli-rails.git
  revision: 7badc2581e0158bb8017cf5a24a39ea8d50b77df
  specs:
    ember-cli-rails (0.5.6)

**Comment by kozak** [comment]
Narrowed it down to a custom index page: 
when using: 
```ruby
  mount_ember_app :adminr, to: "/adminr", controller: "adminr", action: "index"
```

**Comment by kozak** [comment]
Ok, so I think the problem is that I was using `ActionController::Base` which doesn't include the `EmberCli::ControllerExtension`. 

Adding `include EmberCli::ControllerExtension` solved the problem.

**Comment by seanpdoyle** [comment]
@kozak right!

I was just in the process of answering you.

Is the assumption that users will be extending `ApplicationController` a bad one? 

Ideally this gem would omit the [controller exception](https://github.com/thoughtbot/ember-cli-rails/blob/7badc2581e0158bb8017cf5a24a39ea8d50b77df/lib/ember_cli/controller_extension.rb) from its public API.

Would mentioning that your custom controller must extend from `ApplicationController` be enough of a fix for this, or is there a compelling reason to NOT assume you'd extend `ApplicationController`?

**Comment by kozak** [comment]
I think your assumption was good :). 
I've decided to use ActionController::Base (long ago, before using ember-cli-rails, so I it was harder to notice at first), since the controller serving the ember application doesn't require all the other logic that is normally present in ApplicationController. 
Might have been a case of premature optimization on my part. I will switch to using ApplicationController now.
Adding that to the documentation should be enough :)

**Comment by seanpdoyle** [comment]
@kozak :+1: please weigh in on https://github.com/thoughtbot/ember-cli-rails/pull/322

**Comment by kozak** [comment]
Thanks a lot !
