### ISSUE TITLE
Development Cache

### ISSUE THREAD

**Issue by philipp-spiess** [thoughtbot/ember-cli-rails#328]
Is it somehow possible to keep a development cache? I'm running a few capybara specs on top of ember-cli-rails and they need to rebuild the whole Ember app all the time. It should be possible to cache the result and just rebuild what has changed (The same way it works currently when you have a rails server running in development). I also don't want to rebuild the whole Ember App when I restart the rails server.

Edit:

Looking in the code revealed that this would not be a simple task because the recompiling requires --watch and while the rails server process is not running, it won't be able to tell which file have been changed and thus won't trigger a prober rebuild on the next start. We could add something like md5 hashes after every build. Maybe this is something that needs to be improved on `ember-cli` directly.

**Comment by seanpdoyle** [comment]
@philipp-spiess thanks for opening this issue.

This is something that is on our radar, but like you're mentioned, might not be easy to accomplish.

PRs are welcome!
