### ISSUE TITLE
Directory not empty @ dir_s_rmdir [...]/tmp/ember-cli-*

### ISSUE THREAD

**Issue by patcoll** [thoughtbot/ember-cli-rails#329]
I am somehow having trouble and getting the following error when starting up fresh.

If I shutdown and run everything again, I no longer get the error. It appears to be a race condition where `rmtree` encounters a non-empty directory when it expects an empty directory.

Patch with `FileUtils.rm_rf` forthcoming.

---

    Directory not empty @ dir_s_rmdir - /Users/collins/git/<app>/tmp/ember-cli-48b72be5-2bbc-4172-b2fd-9985ebccc426
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:1444:in `rmdir'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:1444:in `block in remove_dir1'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:1455:in `platform_support'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:1443:in `remove_dir1'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:1436:in `remove'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:778:in `block in remove_entry'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:1493:in `ensure in postorder_traverse'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:1493:in `postorder_traverse'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:776:in `remove_entry'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:634:in `block in rm_r'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:630:in `each'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:630:in `rm_r'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/pathname.rb:575:in `rmtree'
    /Users/collins/git/<app>/gems/gems/ember-cli-rails-0.5.7/lib/ember-cli-rails.rb:68:in `each'
    /Users/collins/git/<app>/gems/gems/ember-cli-rails-0.5.7/lib/ember-cli-rails.rb:68:in `cleanup'
    /Users/collins/git/<app>/gems/gems/ember-cli-rails-0.5.7/lib/ember-cli-rails.rb:35:in `enable!'
    /Users/collins/git/<app>/gems/gems/ember-cli-rails-0.5.7/lib/ember_cli/engine.rb:9:in `block in <class:Engine>'
    /Users/collins/git/<app>/gems/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
    /Users/collins/git/<app>/gems/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
    /Users/collins/git/<app>/gems/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    /Users/collins/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    /Users/collins/git/<app>/gems/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
    /Users/collins/git/<app>/gems/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
    /Users/collins/git/<app>/config/environment.rb:5:in `<top (required)>'
    /Users/collins/git/<app>/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    /Users/collins/git/<app>/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    /Users/collins/git/<app>/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/collins/git/<app>/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    /Users/collins/git/<app>/gems/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:236:in `boot_system'
    /Users/collins/git/<app>/gems/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:49:in `run'
    /Users/collins/git/<app>/gems/gems/sidekiq-4.0.1/bin/sidekiq:13:in `<top (required)>'
    /Users/collins/git/<app>/gems/bin/sidekiq:23:in `load'
    /Users/collins/git/<app>/gems/bin/sidekiq:23:in `<main>'
    exited with code 13

**Comment by seanpdoyle** [comment]
Closed by https://github.com/thoughtbot/ember-cli-rails/commit/9960e5842acf6899f0e2beaebe7c774b7971a1fa

**Comment by seanpdoyle** [comment]
Released in https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.5.8

**Comment by patcoll** [comment]
Amazing release turnaround. Thanks Sean!
