### ISSUE TITLE
Required version of cocaine too low in gemspec

### ISSUE THREAD

**Issue by kayakyakr** [thoughtbot/ember-cli-rails#337]
With cocaine 0.5.4, I get: ``undefined method `empty?' for #<Pathname>``. I'm receiving this error when the system first attempts to launch ``ember build --watch``

It is tangentially related to this PR: https://github.com/thoughtbot/ember-cli-rails/pull/86 where Pathnames are not strings.

Upgrading to cocaine 0.5.8 makes the problem go away, so there needs to either be a readme note or a gemspec required version bump.

**Comment by seanpdoyle** [comment]
Thanks for bringing this to our attention.

Would you mind trying out https://github.com/thoughtbot/ember-cli-rails/pull/338?

**Comment by kayakyakr** [comment]
Tried. It selects the expected version of cocaine, doesn't throw errors.
