### ISSUE TITLE
README references old config values

### ISSUE THREAD

**Issue by egh** [thoughtbot/ember-cli-rails#339]
The README contains the following text:

> Alternatively, if you want to override the default behavior in any given Rails environment, you can manually set the `config.use_ember_middleware` and `config.use_ember_live_recompilation` flags in the environment-specific config file.

These configuration flags do not exist in the codebase. I assume this information is outdated?

**Comment by seanpdoyle** [comment]
@egh thanks for bringing this to our attention!

**Comment by egh** [comment]
Thanks! I can easily file a pull request to fix the documentation, but I'm not sure if these have been replaced with other settings.

**Comment by seanpdoyle** [comment]
@egh they haven't been replaced, they're now obsolete.

I'd gladly review a PR fixing up the docs.

**Comment by egh** [comment]
#341

**Comment by seanpdoyle** [comment]
https://github.com/thoughtbot/ember-cli-rails/pull/341#issuecomment-163485946

> Thanks a lot for these updates!

> Luckily, we're working on a substantial overhaul to the README in a separate PR (https://github.com/thoughtbot/ember-cli-rails/pull/336).

> Closing this PR in favor of https://github.com/thoughtbot/ember-cli-rails/pull/336.
