### ISSUE TITLE
No `build` method

### ISSUE THREAD

**Issue by mufid** [thoughtbot/ember-cli-rails#346]
In `README`, we are instructed to do

```
EmberCLI.build("frontend")
```

for manual building. However, it does not work. When i try to `ls` EmberCLI, there is no such method.

```
[5] pry(EmberCli):1> ls EmberCLI
constants: 
  App     BuildError    Capture  Configuration  ControllerExtension  EmberController  Helpers   MissingManifest  Runner  Sprockets
  Assets  BuildMonitor  Command  Constraint     DependencyError      Engine           HtmlPage  PathSet          Shell 
EmberCli#methods: []  app  apps  compile!  configuration  configure  enable!  env  install_dependencies!  root  skip?  test!
EmberCli#methods: []  app  apps  compile!  configuration  configure  enable!  env  install_dependencies!  root  skip?  test!
instance variables: @enabled  @env  @root  @uid
```

Should the readme changed to `compile!` too? Or is there any other recommended way?

**Comment by pubis** [comment]
The commit (c2a80be36404abac6ab2233eb5c272934a0ba32b) that introduced explicit build has not been released yet.

Until released, you should be able to:
```ruby
EmberCli.app(:frontend).build
```

**Comment by seanpdoyle** [comment]
Thanks @pubis, you're right, the README.md is a bit ahead of the game.

@mufid if you're building `0.5.8` (the latest release), read along here:

https://github.com/thoughtbot/ember-cli-rails/blob/v0.5.8/README.md

**Comment by mufid** [comment]
My bad, i didn't notice it was edge version of README. Thanks!

**Comment by seanpdoyle** [comment]
would you mind trying out https://github.com/thoughtbot/ember-cli-rails/pull/347?

It removes the need for the consumer (you) to manually invoke `EmberCli.build`.
