### ISSUE TITLE
Serving ember assets over CDN

### ISSUE THREAD

**Issue by fusion2004** [thoughtbot/ember-cli-rails#353]
With the changes in 0.6.0 to remove the sprockets integration, is there a recommended way to serve the ember assets via CDN rather than just the mounted Rack::File routes?

**Comment by seanpdoyle** [comment]
@fusion2004 you can serve assets over a CDN like you would with any other Ember application --
by prepending the CDN URL:

http://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls

```js
var app = new EmberApp({
  fingerprint: {
    prepend: 'https://subdomain.cloudfront.net/'
  }
});
```

As long as your [CDN first pulls from your Rails application](https://robots.thoughtbot.com/dns-cdn-origin), your assets will be served through it on subsequent calls.

**Comment by seanpdoyle** [comment]
Thanks for bringing this gap in documentation to our attention:

https://github.com/thoughtbot/ember-cli-rails/pull/354

**Comment by fusion2004** [comment]
No problem, it took me a bit to get it to work though.

I'm using the include_* asset helpers to include ember into arbitrary non-root pages, and by default those helpers were outputting paths like `assets/frontend.css` which would not work on non-root pages.

The fix was to enable fingerprinting for all environments, and add a prepend of '/'.

Thanks!

**Comment by seanpdoyle** [comment]
@fusion2004 if you'd like to avoid fingerprinting in all environments, you might want to try out `master`, particularly `mount_ember_assets`:

https://github.com/thoughtbot/ember-cli-rails#mounting-multiple-ember-applications

```rb
# config/routes.rb
Rails.application.routes.draw do
  mount_ember_assets :frontend, to: "/"
end
```
