### ISSUE TITLE
Without Sprockets, ember-cli-rails no longer serves source map.

### ISSUE THREAD

**Issue by kayakyakr** [thoughtbot/ember-cli-rails#359]
Commit [ffb7c2d](https://github.com/thoughtbot/ember-cli-rails/commit/ffb7c2d71f443d993d39a474a9517c318ddd4508) removed the dependency on sprockets, but in doing so, the server no longer either generates or serves a js source map file. What this means for users is that the code is displayed in the developer tools as one giant file instead of a debug-able collection of little files. And when you've got a monolith (my app's generated file is 85,000 lines now), that makes it near impossible to work with.

Is there some gotcha introduced in response to this change, or does sprockets need to be added back in?

**Comment by seanpdoyle** [comment]
@kayakyakr EmberCLI will generate source maps in development, by default.

http://ember-cli.com/user-guide/#source-maps

Have you disabled this configuration?

**Comment by kayakyakr** [comment]
They are being generated, but not served. This is with the ``include_ember_script_tags`` method, if that affects anything?

**Comment by seanpdoyle** [comment]
That's strange, when I run:

https://github.com/seanpdoyle/ember-cli-rails-heroku-example

locally, I'm not seeing that behavior. 

Maybe it's a browser issue? Would you mind cloning that repo and trying to view source code locally?

**Comment by kayakyakr** [comment]
Interesting. My ember app is named "home" and is located in "app/home"

The map file that is being generated is generated as /app/home.map. The source map line that is being added to the compiled home.js is /assets/home/assets/home.map, which sprockets seems to understand, somehow.

Any idea what would be causing that double-nested asset path?

**Comment by seanpdoyle** [comment]
For starters -- probably totally unrelated -- I would recommend that you **DO NOT** nest your frontend in your Rails `app/` directory, as Rails does a lot with that directory, and having an infinitely deep `node_modules` and `bower_components` directory will likely complicate things and add some hiccups to your performance.

**Comment by seanpdoyle** [comment]
@kayakyakr given the `/assets/home` prefix in your `/assets/home/assets/home.map` path, it looks like you're either:

* prepending onto your path from `home/ember-cli-build.js`
* a `<base href="/assets/home">` tag is messing with some paths

Are either of those assumptions accurate?

**Comment by kayakyakr** [comment]
```Javascript
/*jshint node:true*/
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    minifyJS: {
      enabled: false
    },
    storeConfigInMeta: false
  });

  app.import('vendor/ember-droplet/controller.js');
  app.import('vendor/ember-droplet/view.js');
  app.import('vendor/ember-typeahead.js');

  return app.toTree();
};
```

and

```ERB
<base href="/">
<%= include_ember_script_tags :home %>
```


And good to know about the app, though it feels dirty to me to not have that be nested under the app tree.

**Comment by seanpdoyle** [comment]
@kayakyakr what version of https://github.com/rondale-sc/ember-cli-rails-addon/ are you on?

**Comment by kayakyakr** [comment]
``"ember-cli-rails-addon": "rondale-sc/ember-cli-rails-addon#sd-build-error"``

That's the un-merged PR 24.

**Comment by kayakyakr** [comment]
That was it. Upgraded and it works.

**Comment by kayakyakr** [comment]
Thanks @seanpdoyle, sorry for wasting a bunch of your afternoon on version incompatibilities.

**Comment by seanpdoyle** [comment]
:clap: thanks for opening this issue!

**Comment by seanpdoyle** [comment]
No sweat! I'm at fault too, I'm the one who told you to try out that feature branch

**Comment by henrymazza** [comment]
Got bitten by the wrong addon version too! Time to raise a warning?!

**Comment by kayakyakr** [comment]
Don't want to write a new issue for this: For some reason, in my staging environment, I'm seeing an ``ember build --watch  --environment 'development'`` being launched. From what I can tell from the code, it shouldn't be launching a build and watch command, but it is.

**Comment by kayakyakr** [comment]
Ah, hm, this might actually be worth a new issue.

**Comment by seanpdoyle** [comment]
@kayakyakr please open the issue, but I have a hunch it has to do with:

https://github.com/thoughtbot/ember-cli-rails/blob/7e8cd937ea097b8ec36251a06d647405420e5a9a/lib/ember_cli/helpers.rb#L27

If you set `config.consider_all_requests_local = false` it should treat it as a production environment.

That's been in the code base long before I inherited it, so I don't quite understand the repercussions of removing it.

Please open the issue and I'll try to resolve it with improvements to the README

**Comment by kayakyakr** [comment]
Yeah, that's exactly what it was. I'll open a new issue, but I don't know if there will be an action taken.
