### ISSUE TITLE
Bower assets

### ISSUE THREAD

**Issue by henrymazza** [thoughtbot/ember-cli-rails#360]
On 0.6.0 these paths stopped working:
```

  <script src="/assets/frontend/assets/intl/intl.min.js"></script>
  <script src="/assets/frontend/assets/intl/locales/en-us.js"></script>
```
Were there changes on how to get these bower assets?

**Comment by kayakyakr** [comment]
This might be the same thing I was just hit with. Are they accessibly under `/assets/intl/...` ? Did you upgrade your version of ember-cli-rails-addon to the most recent master?

**Comment by seanpdoyle** [comment]
@henrymazza was this related to https://github.com/thoughtbot/ember-cli-rails/issues/359#issuecomment-164933675?

Is this resolved?

**Comment by henrymazza** [comment]
No! Actually the version didn’t help! 
Found what was wrong, the path changed from 

`/assets/frontend/assets/intl/intl.min.js`

to

`/home/assets/intl/intl.min.js`

My route.rb is configured as:

`mount_ember_app :frontend, to: "/home/", controller: "home", action: “index"`


I think it must be due to the elimination of Sprockets as a dependency, right!? I don’t know if the latter form resolved to any route before.

-- 
Fabio Mazarotto

On 15 de dezembro de 2015 at 23:51:22, kayakyakr (notifications@github.com) wrote:

This might be the same thing I was just hit with. Are they accessibly under /assets/intl/... ? Did you upgrade your version of ember-cli-rails-addon to the most recent master?

**Comment by henrymazza** [comment]
Actually the `ember-cli-rails-addon` version didn’t help!
I just found what was wrong, the path must be changed from 
`/assets/frontend/assets/intl/intl.min.js`
to
`/home/assets/intl/intl.min.js`

My route.rb is configured as:

`mount_ember_app :frontend, to: "/home/", controller: "home", action: “index"`

I think it must be due to the elimination of Sprockets as a dependency, right!? I don’t know if the latter form resolved to any route before.

**Comment by henrymazza** [comment]
It's the third time in a few versions it changes! Luckly it's an edge case and the latest is the best so far! 👍

**Comment by seanpdoyle** [comment]
> the path must be changed from `/assets/frontend/assets/intl/intl.min.js` to `/home/assets/intl/intl.min.js`

@henrymazza are you managing the creation of this URL yourself? The version upgrade should have handled this for you without developer intervention.

**Comment by henrymazza** [comment]
Yes, I’m. Is there any way to make it automatic? I’m following this guide: https://github.com/yahoo/ember-intl/wiki/Intl.js-Polyfill#polyfillio

It’s the only case, any other asset i’m including through ember-cli-build.js


On 16 de dezembro de 2015 at 14:50:24, Sean Doyle (notifications@github.com) wrote:

the path must be changed from /assets/frontend/assets/intl/intl.min.js to /home/assets/intl/intl.min.js

@henrymazza are you managing the creation of this URL yourself? The version upgrade should have handled this for you without developer intervention.

**Comment by seanpdoyle** [comment]
@henrymazza if you're using pollyfill.io, the `<script>`'s `src` attribute should be a fully qualified URL, right:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>
```

If not, are you using the `render_ember_app` helper, or the `include_ember_*_tags` helpers?

If you're rendering the EmberCLI-generated `index.html`, I recommend you add the `<script>` tag (with `src` set to a relative path) to your Ember application's `index.html`, so that it will be managed by `ember-cli` and not Rails.

If you're using the `include_ember_*_tag`, you're on your own in terms of managing the URL. I highly recommend you migrate toward using `render_ember_app`.

**Comment by henrymazza** [comment]
Not using polyfill, just forgot the anchor! I'm using `include_ember_*_tags` so i'm having to manage urls myself. I'll change it to `render_ember_app` and see who it goes.

I have shared stylesheets between the legacy rails app and the new ember frontend so using ember-cli's index.html isn't an option.

Thank you for the help.

**Comment by kayakyakr** [comment]
I have had some success in keeping things that get globally included in the rails assets instead of in ember and just including application.js. Pulling in jquery, bootstrap, all sorts of things from rails via the traditional asset pipeline.

**Comment by seanpdoyle** [comment]
@kayakyakr that's a good point. 

@henrymazza during your transition, you could include the polyfill in Rails via Sprockets and embed the script tag in your Rails view using the normal asset pipeline script tag helpers

**Comment by henrymazza** [comment]
@seanpdoyle Good idea.

just another thing, `include_ember_*_tags` isn’t working anymore. When loading through deeper route (like reloading a nested resource) it generates the wrong link. Like so on my app:

Loading `http://localhost:3000/home/sales` loads `http://localhost:3000/home/assets/vendor.js`
but
`http://localhost:3000/home/sales/190` loads `http://localhost:3000/home/sales/assets/vendor.js`

Can you confirm it?

**Comment by kayakyakr** [comment]
did you use the <base href="/home"> tag?

**Comment by henrymazza** [comment]
@kayakyakr Wow! Sorry! This readme changed a lot since I first read it. I'll read it through and talk to you later! :smile:
