### ISSUE TITLE
rails server crashing

### ISSUE THREAD

**Issue by sebyx07** [thoughtbot/ember-cli-rails#369]
I've started a new project with ember cli 1.13.13, rails 4.2.5, ruby 2.2.4. I've mounted the ember application with ```mount_ember_app :app, to: '/app'```, 
but whenever i go that route the server gets into a deadlock state. The webservers i tried: webrick, thin and puma and all gave the same results. 
The build happens because and it's successfull. there are files in ```tmp/ember-cli```

**Comment by seanpdoyle** [comment]
@sebyx07 thanks for opening this issue!

What version of the gem and what version of the addon are you running?

**Comment by sebyx07** [comment]
```
remote: git://github.com/thoughtbot/ember-cli-rails.git
  revision: 9ebe866ce032bc2804b85fe751b1c763449fe465
  specs:
    ember-cli-rails (0.7.0)
      cocaine (~> 0.5.8)
      ember-cli-rails-assets (>= 0.6.1)
      html_page (~> 0.1.0)
      railties (>= 3.2, < 5)

"ember-cli-rails-addon": "0.6.0"
```

ok i forgot to add the ember addon to the ember application. But now i'm getting 404 for the assets in the index.html ember app
```
assets/vendor.css
assets/my_app.css
assets/vendor.js
```

**Comment by sebyx07** [comment]
i forgot to add to routes
``` ruby
mount_ember_assets :app, to: '/'
```

**Comment by seanpdoyle** [comment]
@sebyx07 thanks for the extra context.

Have you looked at https://github.com/seanpdoyle/ember-cli-rails-heroku-example? It has example code for how to get `ember-cli-rails` up and running, and you might be able to spot the differences in your configuration.

I'm glad to head the addon resolved your locking issue.

**Comment by seanpdoyle** [comment]
@sebyx07 `mount_ember_assets :app, to: '/'` shouldn't be necessary..

**Comment by seanpdoyle** [comment]
@sebyx07 since you're mounting to `"/app"` instead of `"/"`, there are some additional steps:

https://github.com/thoughtbot/ember-cli-rails#mounting-multiple-ember-applications

**Comment by seanpdoyle** [comment]
@sebyx07 have you tried out https://github.com/thoughtbot/ember-cli-rails/issues/369#issuecomment-166315181?

**Comment by seanpdoyle** [comment]
This issue has become stale, and it looks like you've resolved your problems.

Closing.

If the problem persists, please ping me and I'll re-open.
