### ISSUE TITLE
Docs: inheriting the default controller and adding before-filters

### ISSUE THREAD

**Issue by nruth** [thoughtbot/ember-cli-rails#373]
Great work on reviving this gem, in particular `render_ember_app`!

I'd like to suggest documenting how to add before-filters without duplicating the controller implementation. 

For example, the following adds Devise authentication before sending the index page (security through obscurity for the JS file URLs, which may be desirable for admin applications).

```ruby
# routes, assuming authentication already set up
mount_ember_app :admin_panel, to: "/", controller: 'authenticated'

# app/controllers/authenticated_controller.rb
class AuthenticatedController < EmberCli::EmberController
  before_action :authenticate_admin_user!
end
```

If this looks ok I'll make a PR for the readme and add a test if there isn't one.
I'm asking first because I think this is adding something to the public API?

**Comment by seanpdoyle** [comment]
Thanks for opening this issue!
Could you elaborate on your use case -- I don't understand the reasoning behind extending `EmberCli::EmberController` (instead of `ApplicationController`).

[`render layout: false`](https://github.com/thoughtbot/ember-cli-rails/blob/1d06d46a822c608958027a836e5815295898b1de/app/controller/ember_cli/ember_controller.rb#L4) is the only meaningful behavior, and [that's already documented](https://github.com/thoughtbot/ember-cli-rails/blob/1d06d46a822c608958027a836e5815295898b1de/README.md#overriding-the-controller).

**Comment by nruth** [comment]
Thanks for reading! I don't mind if this gets rejected, just trying to give something back.

I was originally going to suggest a readme/wiki example for authentication or adding controller before-filters, but noticed that this way of extending the controller seems more like the root cause of why I found it fiddly to set up. Improving that (if it does) seemed more valuable than making the readme longer.

It's part laziness and part future-proofing, or perhaps just personal preference. I think it simplifies set-up where mostly default behaviour is needed.

This is all a bit tenuous because there aren't that many concepts or lines of code involved.

#### Use case: authentication / adding controller callbacks / filters

My use case is adding authentication (to protect the app source), by inserting a Devise before-filter for one of the two Ember apps hosted by this gem. For instance :frontend served to everyone, but :admin_panel only served to logged-in admins.

#### Maintenance

This can be done following the readme, but it means duplicating two files from the gem: the controller and the view. That's fine until they change in the gem, and the copies in the app get left behind?

Since the controller is very simple and the view template uses `render_ember_app ` this seems like a moot point.

#### Simplicity

The other issue is simplicity. This gem is really simple to use out of the box. You don't need to understand `render_ember_app`, how the CSRF injection works, or what the controller is doing.

However, to tweak the behaviour of the controller, you need to duplicate all of this in your app (going by the readme). I thought this seemed off, and tried to cut back the duplication a bit, ending up with the example I posted originally.

The first cut was to replace the template file with rendering the one from the gem. I don't remember the correct path, but something like `render 'ember-cli-rails/ember-controller/index', layout: false`

The second cut was to extend the controller, as in the example I originally posted. I was surprised that this worked. It seems like a nice quick way to add before-filters without adding a lot of code.

WDYT?

**Comment by seanpdoyle** [comment]
@nruth sorry that this has sat silently for so long.

There are a multitude of ways to secure a Rails route, ranging from routing constraints to controller logic. I'm not sure this project wants to get involved in advising users on how they should secure their applications.

Having said that, I'd love to see this in a PR to the README, or a separate `.md` document. Once we have it all written out in a PR, we could provided better, more focussed feedback.

I'm closing this issue for now and I look forward to the PR.
