### ISSUE TITLE
GET assets/{vendor,app}.{js,css} 404 not found

### ISSUE THREAD

**Issue by jeffreybiles** [thoughtbot/ember-cli-rails#374]
The `index.hmtl` file can correctly locate the javascript and css files when running `ember server`, but fails to find them when being served via `ember-cli-rails`.

I'm using ember-cli-rails 0.7.0 on Mac OSX with ember-cli 1.13.13, rails 4.1.0, and Ember 1.13.11.

Here's the template that I'm using in Rails.

```erb
<div class="container">
  <base href="/ember_admin">
  <%= include_ember_script_tags :ember_admin %>
  <%= include_ember_stylesheet_tags :ember_admin %>
</div>
```

And here's the fairly standard `index.html` I'm using in my Ember app:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EmberAdmin</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/ember-admin.css">

    {{content-for 'head-footer'}}
  </head>
  <body>
    {{content-for 'body'}}

    <script src="assets/vendor.js"></script>
    <script src="assets/ember-admin.js"></script>

    {{content-for 'body-footer'}}
  </body>
</html>
```

The error I'm getting is `GET http://localhost:3000/assets/ember-admin.js 404 (Not Found)` (and 3 other variations upon that).

Do you know common causes of this?  Is there any other information I should give that would be helpful in debugging this?

**Comment by seanpdoyle** [comment]
@jeffreybiles thanks for opening this issue!

How have you [mounted the Ember assets in your `routes.rb` file](https://github.com/thoughtbot/ember-cli-rails#mounting-multiple-ember-applications)? If so, to what path?

When you access the app through `ember-cli-rails`, what is the base URL? Is it `/ember_admin`? If not, does removing the `<base>` tag resolve this issue?

**Comment by jeffreybiles** [comment]
Thanks for the quick response!

The base url for the ember administration app is indeed `/ember_admin`.  

Here are the `ember-cli-rails`-related things I have in my routes.rb:

```
  get 'ember_admin', to: 'pages#ember_admin'
  get 'organization_admin', to: 'pages#organization_admin'
  mount_ember_assets :ember_admin, to: "/ember_admin"
  mount_ember_assets :organization_admin, to: "/organization_admin"
```

I've also tried it with `mount_ember_app` instead of `mount_ember_assets` with no obvious change.

One thing I hadn't been doing before was including the fingerprinting, so now I added the following code based on the link you gave above (although it doesn't seem to change anything)

```
  var app = new EmberApp(defaults, {
    fingerprint: {
      // matches the `/ember_admin` mount point
      prepend: 'localhost:3000/ember_admin',
    }
  });
```

**Comment by seanpdoyle** [comment]
@jeffreybiles thanks for the extra context.

For starters, you'd be better off using the `mount_ember_app` route helper, since it mounts assets and handles splatting child routes:

```rb
# config/routes.rb

mount_ember_app :ember_admin, to: "/ember_admin", controller: "pages", action: "ember_admin"
mount_ember_app : organization_admin, to: "/organization_admin", controller: "pages", action: "organization_admin"
```

> I added the following code based on the link you gave above (although it doesn't seem to change anything)

By default, Ember CLI won't prepend your fingerprint to the URL in anything but production. If you want to force fingerprinting (you probably shouldn't, but it might help you debug) you should set prepend to a URL that ends in `/`:

```js
// ember-cli-build.js

  var app = new EmberApp(defaults, {
    fingerprint: {
      enabled: true,
      prepend: '//cdn.example.com/ember_admin/',
    }
  });
```

Have you read [Mounting multiple Ember applications](https://github.com/thoughtbot/ember-cli-rails#mounting-multiple-ember-applications):

```js
// ember_admin/config/environment.js

module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'ember-admin',
    environment: environment,
    baseURL: '/ember_admin', // used to be '/'
    // ...
  }
};
```

**Comment by jeffreybiles** [comment]
Aaaaand it works!!!!!

I changed the following two things (both of which seem to be necessary):

1) Used the `routes.rb` configuration that you gave me.
2) Changed the `href` of the `<base>` tag to have a slash at the end.
(the baseURL was already set)

Thank you so much for your help!
