### ISSUE TITLE
Ember-cli hangs due to wrong npm package version

### ISSUE THREAD

**Issue by jboler** [thoughtbot/ember-cli-rails#375]
When I generate an empty Rails 4.2.5 app and follow the basic instructions to add ember-cli, the ember app builds but the browser times out.

See repo https://github.com/jboler/ember-cli-broken

If I change `"ember-cli": "1.13.8",` to `"ember-cli": "1.13.11",` in package.json then it works.

**Comment by seanpdoyle** [comment]
@jboler thanks for opening this issue!

We used to programatically enforce EmberCLI (and other NPM dependencies') versions, but it became too tedious.

[We mention our EmberCLI support in the first paragraph of the README](https://github.com/thoughtbot/ember-cli-rails#ember-cli-rails), as well as [here](https://github.com/thoughtbot/ember-cli-rails#embercli-support).

**Comment by Leooo** [comment]
Updating from an old ember-cli-rails version, It took me hours before understanding why the app was hanging when seeing this issue. I did try to read three times carefully all the setup instructions but still missed the line about using the right ember-cli version. May be worth highlighting this line further down in the instructions.
