### ISSUE TITLE
Is the use of CDN in production a must

### ISSUE THREAD

**Issue by devmarwen** [thoughtbot/ember-cli-rails#378]
I'm starting a new project and trying to decide between `ember-rails` and `ember-cli-rails` **gems** ...
Reading through the documentation, in the **Deploy** section:
>In production environments, assets should be served over a Content Delivery Network.

Is using a **CDN** in production a must? What if I do just want my assets to be served like normal, is there a workaround.

Thanks for your time :smile:

**Comment by seanpdoyle** [comment]
@devmarwen although serving assets over a CDN is highly recommended, it is not necessary.

Check out https://github.com/seanpdoyle/ember-cli-rails-heroku-example for a working example.
