### ISSUE TITLE
No `ember-cli` executable found for `frontend`. Install it:

### ISSUE THREAD

**Issue by rhysdavies1994** [thoughtbot/ember-cli-rails#392]
This is my first time setting up an app with EmberJS and the ember-cli-rails gem.
I've followed the steps in the readme for this git, but when i go to my index page i get the following error:

No `ember-cli` executable found for `frontend`. Install it:
it tells me to run npm install, which changes nothing.

I'm working on Windows 7.

Has anyone else had this issue?

**Comment by seanpdoyle** [comment]
@rhysdavies1994 thanks for opening this issue!

Where is the `frontend` directory relative to your Rails app?

Does `frontend/package.json` declare `"ember-cli"` as a dependency?

If so, what version of `"ember-cli"` is declared as a dependency?

Does `frontend/node_modules/.bin/ember-cli` exist? If so, is it executable?

**Comment by rhysdavies1994** [comment]
@seanpdoyle 
the frontend is stored in the root directory of my rails app. e.g my rails folder is called "learning-ember" generated from "rails new learning-ember". the frontend folder is "learning-ember/frontend".

From what I can see it looks to declare "ember-cli" : "1.13.15" under devDependencies

There is a bunch of ember-cli folders in "frontend/node_modules", although inside of .bin there is only "ember" and "ember.cmd"

I've attached a few files. An image of the error, full trace and my package.json file to assist you.

[ember-cli-rails error.png](https://cloud.githubusercontent.com/assets/7247102/12553073/4a626b28-c3b0-11e5-8ab8-a94811e47c84.PNG)
[ember-cli-rails-full-stack.txt](https://github.com/thoughtbot/ember-cli-rails/files/103303/ember-cli-rails-full-stack.txt)
[package.json.txt](https://github.com/thoughtbot/ember-cli-rails/files/103302/package.json.txt)

**Comment by seanpdoyle** [comment]
> There is a bunch of ember-cli folders in "frontend/node_modules", although inside of .bin there is only "ember" and "ember.cmd"

My mistake -- `ember` is the name we're looking for. There is both an `ember.cmd` and `ember` version?

**Comment by patcoll** [comment]
This seems to happen to me as well.

Oddly, it only occurs locally when running `wercker build`, which, because I'm on Mac OS X, requires a setup using VirtualBox and `docker-machine`. Builds run fine on Wercker in the cloud. This happens with no other CI setup we have. (We're currently evaluating Travis-CI, CircleCI, Wercker, and a local Jenkins instance, all which have different instantiations of running Docker for CI purposes.)

**Comment by staylorwr** [comment]
I'm getting the same issue on Heroku.

The gem works just fine for local development, but after a successful run through the node-js buildpack, and gem install, the asset pipeline fails.


<img width="892" alt="screen shot 2016-01-29 at 12 36 50 pm" src="https://cloud.githubusercontent.com/assets/2738409/12684531/09591b7c-c685-11e5-82cb-5967860accce.png">

**Comment by seanpdoyle** [comment]
@staylorwr just to keep this issue on track and make sure that you're issues are related to https://github.com/thoughtbot/ember-cli-rails/issues/392#issue-128490648, could you clarify whether or not you've followed the [instructions for setting up Heroku](https://github.com/thoughtbot/ember-cli-rails#heroku)?

**Comment by staylorwr** [comment]
Hey @seanpdoyle.  I've followed the instructions and already had the buildpack setup as instructed from compiling a React app.

I've started down the road of deploying production like environments with `ember-cli-deploy` and redis, but this does seem to be a similar issue.

**Comment by seanpdoyle** [comment]
@staylorwr @patcoll @rhysdavies1994 would you please try out #395 (i.e. the `ember-executable-path` branch) and let me know if that resolves your issues?

**Comment by henrebotha** [comment]
@seanpdoyle I've got the same problem. I would like to try this branch you mention but I'm not sure how to do this - could you post/link instructions?

**Comment by seanpdoyle** [comment]
@henrebotha @patcoll @rhysdavies1994 to test the branch out on your project, specify the GitHub org/repo and branch in your `Gemfile`:

```rb
gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails", branch: "ember-executable-path"
```

**Comment by henrebotha** [comment]
@seanpdoyle I did as you suggested, still got the same issues after `npm install`. I ended up doing `rm -r node_modules && npm install`, now it seems to be working.

**Comment by patcoll** [comment]
Yes that did seem to solve my problem!

**Comment by seanpdoyle** [comment]
#395 has landed in the [`0.7.1` release](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.7.1) and the `ember-executable-path` has been deleted.

**Comment by seanpdoyle** [comment]
Closing this issue.

Please reopen if the problem persists past the [new release](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.7.1).

**Comment by patcoll** [comment]
Thank you Sean.

**Comment by 1vanhelsing1** [comment]
We are still getting the issue described, but only when trying to run dev webserver on windows, not on Mac
![errors](https://cloud.githubusercontent.com/assets/5320436/17622698/2f24f73e-609c-11e6-9b5f-b7f709b4882c.PNG)

**Comment by wowiamhere** [comment]
#### Hello,  
## Having same issue here.  
Followed all instructions at https://github.com/thoughtbot/ember-cli-rails/blob/master/README.md  

**Getting this error**:

![ember-cli-rails-no-executable-issue](https://cloud.githubusercontent.com/assets/12240664/18037818/df953d0c-6d41-11e6-9395-d149d25a4a26.png)  
![ember-cli-rails-dir](https://cloud.githubusercontent.com/assets/12240664/18037821/1a7d448c-6d42-11e6-8a24-cf2a2c909bd2.png)  
![ember-cli-rails-packagejson](https://cloud.githubusercontent.com/assets/12240664/18037862/7a7402fe-6d42-11e6-8c19-6f319e1a1a09.png)  

Not sure how to proceed.  
Please advise.  

Thanx
sergio
