### ISSUE TITLE
Live Reload?

### ISSUE THREAD

**Issue by nerdyworm** [thoughtbot/ember-cli-rails#393]
Is there any way to wire up live reload?  Or is there an alternative that works?

**Comment by seanpdoyle** [comment]
@nerdyworm the [`README.md` used to explain how to enable LiveReload through `guard`](https://github.com/thoughtbot/ember-cli-rails/blob/0eebed8ca8859c28bbe10633b7dc3d7b24bd999a/README.md#enabling-livereload).


It's possible -- and might be worth revisiting -- but official "support" was dropped in favor of stabilizing the gem by reducing scope and focussing in on a smaller set of features.

[This commit](https://github.com/thoughtbot/ember-cli-rails/commit/ffb7c2d71f443d993d39a474a9517c318ddd4508) removed that explanation.

**Comment by nerdyworm** [comment]
Thanks for the explanation and history.

In a non ember-cli-rails app we just insert the ember-cli-live-reload.js script manually.  This does require the ember cli server to be running, so that may not be ideal for this workflow.

Guard live reload seems like a good enough solution.

I'm going to close this as it is not critical, it just needs to show up in search history.

Cheers!

**Comment by seanpdoyle** [comment]
Thanks @nerdyworm !
