### ISSUE TITLE
ember:install should blow away deps and reinstall from scratch if ember version says so?

### ISSUE THREAD

**Issue by botandrose** [thoughtbot/ember-cli-rails#394]
Ember CLI ships with [ember-cli-dependency-checker](https://github.com/quaertym/ember-cli-dependency-checker), which provides the `ember version` command, which is akin to `bundle check`. I have enhanced the `ember:install` rake task to `rm -rf node_modules` before installing if `ember version` returns non-zero.

This seems like something that might belong in Ember CLI Rails itself. WDYT? Should I prepare a PR?

**Comment by seanpdoyle** [comment]
@botandrose that sounds like a great idea.

> `ember version` command

TIL

**Comment by botandrose** [comment]
Great, I'll begin!

Yeah, I just learned about `ember version` recently myself, while struggling with unreliable builds across different machines. Its basically an attempt to bandaid the insanity that is npm and especially npm shrinkwrap. If only npm would adopt semantics like Gemfile.lock. :/

**Comment by seanpdoyle** [comment]
Closed by https://github.com/thoughtbot/ember-cli-rails/commit/6eceea8a9321e3c38e2425e5f39124912ad297af.
