### ISSUE TITLE
Getting define is not defined in console

### ISSUE THREAD

**Issue by meliborn** [thoughtbot/ember-cli-rails#397]
```
ember version
version: 2.3.0-beta.1
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.2
npm: 2.14.10
os: darwin x64
```
![frontend 2016-01-30 03-51-18](https://cloud.githubusercontent.com/assets/735194/12692173/c5596122-c704-11e5-8da7-fd747862489f.jpg)
But, it works with ```ember s```

**Comment by seanpdoyle** [comment]
@meliborn thanks for opening this issue!

Are you using the `render_ember_app` helper?

If so, I have a hunch this is related to `ember-cli@2.3.0-beta.1`, as [ember-cli has had issues with this in the past](https://github.com/ember-cli/ember-cli/search?utf8=%E2%9C%93&q=%22define+is+not+defined%22&type=Issues), and `ember-cli-rails` doesn't do anything but serve the output (directly, not through Sprockets / Asset Pipeline) of `ember build`.

Do you have anything else you could share that would help us determine the source of this issue?

**Comment by meliborn** [comment]
@seanpdoyle I didn't do any specific actions. Just fallow instructions. I don't use ```render_ember_app``` helper. 
I just did 
```ember new frontend --skip-git```
```rails generate ember:init```
```ember install ember-cli-rails-addon``` 
 ```rake ember:install```

**Comment by meliborn** [comment]
Seems it was a conflict with ```ember-rails``` gem

**Comment by seanpdoyle** [comment]
@meliborn thanks for clearing that up!
