### ISSUE TITLE
Refused to execute script from because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by meliborn** [thoughtbot/ember-cli-rails#398]
I have an Ember app at /ember, not just /. Here are my routes:

  ```
mount_ember_app :frontend, to: '/ember', controller: 'ember/ember', action: 'index'
mount_ember_assets :frontend, to: "/ember
```

And here is my ember#index view:
```
= include_ember_script_tags :frontend
= javascript_include_tag 'ember/application'
= include_ember_stylesheet_tags :frontend
```

All of this produce the next errors:
![errno enoent at publo 2016-01-31 22-51-57](https://cloud.githubusercontent.com/assets/735194/12704492/4b7472d8-c86d-11e5-84e6-a80d289643fd.jpg)

What interesting, ```vendor.js``` throws me my js files from ember/application rails manifest like this:
![errno enoent at publo 2016-01-31 22-56-10](https://cloud.githubusercontent.com/assets/735194/12704511/d68e024e-c86d-11e5-980d-dceac23c11df.jpg)

**Comment by seanpdoyle** [comment]
@meliborn thanks for opening this issue?

Just to clarify -- are you trying to serve the `ember-cli` generated `index.html` (with `render_ember_app`), or are you trying to inject the `ember-cli` generated JS and CSS files into an existing rails view?

I ask becuase it looks like you're using a mix of helpers from both approaches.

If this is a newly configured `ember-cli-rails` application, I strongly suggest you avoid [rendering the ember-cli generated JS and CSS](https://github.com/thoughtbot/ember-cli-rails#rendering-the-embercli-generated-js-and-css), as it's deprecated.

**Comment by meliborn** [comment]
@seanpdoyle Thanks for response. Seems I really tried to mix both approaches.
On deprecation, how can I include Rails assets in this case? I18n.js for example, which refreshes every time after I make a change in Rails I18n. Or any other JS and CSS files

**Comment by seanpdoyle** [comment]
@meliborn does the [Overriding the view](https://github.com/thoughtbot/ember-cli-rails#overriding-the-view) section describe your use case?

**Comment by meliborn** [comment]
@seanpdoyle Works like a charm, thanx

**Comment by seanpdoyle** [comment]
@meliborn glad we could help work things out!
