### ISSUE TITLE
Coffeescript support?

### ISSUE THREAD

**Issue by meliborn** [thoughtbot/ember-cli-rails#399]
Is it possible for now to use *.coffee files instead of *.js in Ember app folder? I have tried https://github.com/kimroen/ember-cli-coffeescript, but seems it doesn't work because ember-cli-rails take affect on build process.

**Comment by seanpdoyle** [comment]
@meliborn thanks for opening this issue.

Could you please elaborate on this issue, possibly including the particular errors and stack traces you're seeing?

> it doesn't work because ember-cli-rails take affect on build process.

If you're using `render_ember_app` to serve the `ember-cli`-generated `index.html`, there's nothing from the `ember-cli-rails` perspective that should break https://github.com/kimroen/ember-cli-coffeescript support.

What makes you believe this is related to `ember-cli-rails`?

**Comment by meliborn** [comment]
@seanpdoyle Because it's the only one idea I have to explain this issue. There are no any errors, it just doesn't compile .coffee files. Is it possible to make Rails assets pipeline to compile .coffee files?

**Comment by seanpdoyle** [comment]
> Is it possible to make Rails assets pipeline to compile .coffee files?

@meliborn what version of `ember-cli-rails` are you running? We [dropped Sprockets integration in version `0.6.0`](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.6.0). 

Versions after `0.6.0` that use `render_ember_app` server the EmberCLI-generated `index.html` directly, without any involvement in the EmberCLI build process.

**Comment by meliborn** [comment]
@seanpdoyle The latest, 0.7.0

**Comment by seanpdoyle** [comment]
This sounds like an issue with your project's configuration of https://github.com/kimroen/ember-cli-coffeescript.

Closing this for now. 

If you're able to provide some additional information that links your issues to `ember-cli-rails`, I'd love to see it and I'd gladly reopen the issue.

**Comment by seanpdoyle** [comment]
Although it's not using `ember-cli-coffeescript`, https://github.com/seanpdoyle/ember-cli-rails-heroku-example is a good example of a working application running on `0.7.0`.

I encourage you to compare how it's configured with how your project is configured.

**Comment by andrewhavens** [comment]
I also ran into some issues getting `ember-cli-coffeescript` to work, though I seem to have it partially working. There may be some issues as mentioned in this issue: https://github.com/kimroen/ember-cli-coffeescript/issues/86
