### ISSUE TITLE
Set Cache-Control headers for assets

### ISSUE THREAD

**Issue by wireframe** [thoughtbot/ember-cli-rails#401]
Requests for ember assets are being proxied through the `EmberCli::Deploy::File` rack middleware, but does not set any of the HTTP cache control headers from rails.  

Since ember production builds automatically digest the filenames of images/css/js/etc, these files are highly cachable, and should support the standard HTTP caching headers in some way (ex: rails `static_cache_control` config).

**Comment by wireframe** [comment]
It may be possible/preferable to reuse the `ActionDispatch::Static` middleware which is what rails internals use to serve files from the public directory (and automatically sets the cache control headers).

**Comment by seanpdoyle** [comment]
@wireframe that sounds like a great alternative!

Are you familiar enough with [ActionDispatch::Static](https://github.com/rails/rails/blob/4df216cb12e35c09ae5ec271755e581d692d0326/actionpack/lib/action_dispatch/middleware/static.rb#L101) to create a PR?

**Comment by seanpdoyle** [comment]
@wireframe I've thought about this further.

While we'd gladly accept a PR that implemented this functionality, it might not be necessary.

We [encourage users to serve their assets](https://github.com/thoughtbot/ember-cli-rails#deploy) over a [CDN configured to pull from the Rails app](https://robots.thoughtbot.com/dns-cdn-origin).

This means that after the initial pull from origin, the Rails application would no longer serve the fingerprinted assets. 

This limits the impact of Content headers (which are ultimately overwritten by the CDN) to a single request per asset.

**Comment by seanpdoyle** [comment]
Closing this issue for now. 

If you feel strongly about introducing `ActionDispatch::Static`, please open a PR and we can discuss further.

**Comment by wireframe** [comment]
@seanpdoyle every CDN that i've worked with (cloudfront/fastly) acts as a reverse proxy to load resources from rails and then caches them on their edge servers.  The duration of the cache relies 100% on the cache headers sent from the origin server (ie: rails) so the cache headers are extremely important in order to take full advantage of your CDN.  

The thoughtbot blog you linked to actually explains this in detail.  If rails isn't setting the "Cache-Control" header, your CDN will only cache that asset for a fairly short time and the benefit is very limited.

If you're CDN experience is different, I'd love to hear it, but this seems like a pretty standard flow for vanilla rails apps assets + CDN's.

**Comment by seanpdoyle** [comment]
@wireframe thanks for clarifying, those are some good points.

I'll reopen this issue.

**Comment by seanpdoyle** [comment]
@wireframe I've pushed https://github.com/thoughtbot/ember-cli-rails/pull/403. Please weigh in there.
