### ISSUE TITLE
config.eager_load is nil when running rake ember:install

### ISSUE THREAD

**Issue by alvinkatojr** [thoughtbot/ember-cli-rails#404]
I keep getting config.eager_load is nil statement(not sure if its an error) even though eager_load is set to false in both development and test. What could be the issue? 

![screen shot 2016-02-09 at 10 50 41 pm](https://cloud.githubusercontent.com/assets/519988/12928650/b1438b08-cf7f-11e5-8295-ef8c847fc194.png)

**Comment by seanpdoyle** [comment]
@alvinkatojr thanks for opening this issue!

For what it's worth, `ember-cli-rails` doesn't rely on or set `Rails.configuration.eager_load`. 

This appears to be an issue originating in your Rails code.

Have you tried following the suggestions provided in the output you've shared?

Closing this issue, as I don't think it's related to this gem.

**Comment by alvinkatojr** [comment]
By default eager_loading on all all environments save production is set to false so that part is covered. The configuration code seems to be okay as well. 

Prior to my updating the gem and following the related ember-chli-addon instructions I did n't have any of these issues. 

For instance the <code>rake ember:install</code> command does n't really install any dependencies. It just gives me that eager_loading output which is correctly set in my environment file.

**Comment by seanpdoyle** [comment]
@alvinkatojr have you tried running `bundle exec rake ember:install`?

What about `bin/rake ember:install` (assuming you have the [bundler binstubs](http://bundler.io/v1.10/bundle_binstubs.html) installed)?

**Comment by alvinkatojr** [comment]
Unfortunately that does n't work either. I do have binstubs installed. I'll give this break and come back to it later, when I do get it fixed I'll be sure to let you know. 

Thank you for your responsiveness and help @seanpdoyle. Really appreciate it.
