### ISSUE TITLE
frontend.css / vendor.css paths

### ISSUE THREAD

**Issue by Leooo** [thoughtbot/ember-cli-rails#406]
Hello, I'm upgrading from a previous version of ember-cli-rails and I'm finding it hard to understand how things now work.

* I have my ember app under `/frontend/`
* I still have some pages using rails-rendered views, so I'm not using `mount_ember_app` in `routes.rb`, instead I'm using the line `mount_ember_assets :frontend, to: "/"`, and I'm rendering when needed my ember html requests to the `ember/index.html` (empty) view
* My ember/index.html view is using a layout with `include_ember_stylesheet_tags :frontend` and `include_ember_script_tags :frontend`

My problem now is that for any page which is non root (like `http://localhost:3000/profiles/one-user` or `http://localhost:3000/public` for example), when I reload it is looking for Ember stylesheets under the following paths: `http://localhost:3000/profiles/assets/frontend.css` `http://localhost:3000/profiles/assets/vendor.css` (so not using the root path, this should be `http://localhost:3000/assets/frontend.css` and `http://localhost:3000/assets/vendor.css`).

Any idea where this come from?

Thanks

**Comment by seanpdoyle** [comment]
@Leooo thanks for opening this issue and bringing this to our attention.

Have you tried the steps described in the [Mounting Multiple Ember applications](https://github.com/thoughtbot/ember-cli-rails#mounting-multiple-ember-applications) section of the README, particularly:

> Then set each Ember application's `baseURL` to the mount point:

```javascript
// frontend/config/environment.js

module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'frontend',
    environment: environment,
    baseURL: '/',
    // ...
  }
};
```

Have you checked out [my example application](https://github.com/seanpdoyle/ember-cli-rails-heroku-example), particularly [this line](https://github.com/seanpdoyle/ember-cli-rails-heroku-example/blob/4839240afb27c11999a29989fdba6d9c3d034fc9/admin/config/environment.js#L7)?

**Comment by Leooo** [comment]
thanks for quick answer. I tried to infer from the README what to do yes, but in my case I need to keep some pages rendered by rails so I don't think I can use `mount_ember_app` (maybe I will try to put it last in my routes to see if this helps but I don't think so). 

Mounting Multiple Ember applications is not really my use case, I have only one Ember app mounted on the normal `/frontend/` path.

I already had the `baseUrl: '/'` in my app for the previous ember-cli-rails verison which was working fine.

**Comment by Leooo** [comment]
Struggling to understand where this may come from.

Only thing which I can think of is: I'm using `include_ember_stylesheet_tags :frontend` in my layout for the `ember/index.html` view, which is rendered when going to the `http://localhost:3000/public` path (so not the usual ember-cli-rails config), so the stylesheets `frontend.css` etc. seem to be prepended to `http://localhost:3000/public/`, how could I make it prepended to the root path instead?

**Comment by Leooo** [comment]
Hello, could you help in explaining at least where the `frontend.css` and `vendor.css` stylesheets are loaded from in the code? Is it from the `ember-cli-rails-addon` or from the rails gem? it would help in isolating where the problem comes from this prevents development on my app right now. Thanks

**Comment by seanpdoyle** [comment]
@Leooo I'm sorry, I'm not sure what the issue is.

Would you be able to fork [the ember-cli-rails example repo](https://github.com/seanpdoyle/ember-cli-rails-heroku-example) and modify it so that it reproduces the issues you're experiencing?

That way, we can investigate the code diff and have a more concrete discussion about the underlying causes.

**Comment by Leooo** [comment]
ok this was the <base href="/"> tag missing, it is in the docs but so unusual that I just missed it.

Thanks
