### ISSUE TITLE
ember-cli-rails mount cannot be excluded from devise authentication

### ISSUE THREAD

**Issue by Ikariusrb** [thoughtbot/ember-cli-rails#410]
I was attempting to put together a single rails app which hosted an ember-cli-rails frontend and an API back-end with devise authentication, which would allow the user to login within the ember UI (using ember-simple-auth).

After fiddling with the code, I concluded that I couldn't exclude the ember mountpoint from the devise authentication, so I opened an issue with the devise project.

The conclusion from their end was that there was no way to allow this as the ember-cli-rails mount is implemented as a callable constraint rather than as a hash constraint, and so Rails itself is unable to apply both rules.  

Here is the issue which was opened with devise - https://github.com/plataformatec/devise/issues/3977

Is there any way to change the ember-cli-rails mount constraint to a hash constraint so additional rules can be applied to it?

**Comment by seanpdoyle** [comment]
@Ikariusrb thanks for opening this issue, bringing it to our attention.

Also, a big thank you for first opening the issue against Devise for additional context! :+1: 

What code changes do you need to make your use case work?

Would you be able to on a PR against [this line](https://github.com/thoughtbot/ember-cli-rails/blob/b70fe1a6b422d782ac8068fa96164467792f5a6f/lib/ember_cli/route_helpers.rb#L17), with the necessary modifications?

If you can get your use case to work, we could work together to ensure existing behavior still works.

**Comment by Ikariusrb** [comment]
I have to admit, I believe I'm changing my mind for my particular use;  I am now looking at having my ember app require authentication before it can be accessed, and using some static HTML pages with minimal javascript (no full framework) to authenticate users before they are granted to access the ember application. 

On the other hand, I suspect that hosting an ember front-end from the same rails app which provides a back-end API and authentication would likely be a fairly common use-case.  To do that would require the ember app to be served without requiring authentication- user gets the ember app first, then logs in from the ember-provided UI.   

Devise is a pretty common authentication module for rails, and when it is installed, it adds authentication to all routes by default, and the method for configuring an unauthenticated route in config/routes.rb looks like this:

```
  unauthenticated do
    root to: "main#index"
  end

```

I tracked the implementation of that back to https://github.com/plataformatec/devise/blob/master/lib/devise/rails/routes.rb#L318

Unfortunately, that implementation doesn't appear to play nicely with engine mounts, or at least that's my take-away from the devise team's response to the issue I opened with them- it sounds like there are some limitations in applying configuration to routes in rails itself, if I correctly understand their response.  

The line you referenced in ember-cli-rails certainly looks like the place where this would be addressed, if it can be.  If it can't be fixed, at least this issue can stand as documentation that this won't be a fruitful path for others in the future.

**Comment by seanpdoyle** [comment]
Thanks for all that extra context.

> I am now looking at having my ember app require authentication before it can be accessed

We've had success with this approach. One of my favorite aspects of this approach is that the Ember application doesn't need to know anything about authentication (or the current user most of the time), and it depends on the API itself to restrict access / include user-specific context in the responses.

However, utilizing this approach means using both Rails-generated views (in your case Devise's login, password reset, signup, etc.) in addition to the Ember frontend.

Your mileage may vary.

**Comment by ClayShentrup** [comment]
Oh wow, I've been tearing my hair out over this issue for the past 24-36 hours. Strangely, it has alternated back and forth, working then not working for no apparent reason. I suspected some kind of weird race condition, but I honestly don't know. I've done a crazy amount of Ruby stack tracing in my day and this thing takes the cake.

**Comment by ClayShentrup** [comment]
@Ikariusrb 

> Devise is a pretty common authentication module for rails, and when it is installed, it adds authentication to all routes by default

That's totally [not my understanding](https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb). Devise even gives you a `user_signed_in?` method to check whether a user is signed in. If you want to restrict a route to only authenticated users, you have to wrap the route in an `authenticate` block.

Although I am indeed experiencing this issue, so I'm a little confused here.
