### ISSUE TITLE
Do the heroku instructions compile app js at deploy or runtime?

### ISSUE THREAD

**Issue by nruth** [thoughtbot/ember-cli-rails#413]
It doesn't seem to mention it and I'm not sure what the production behaviour is.

- Does it get added to the rails asset precompile
- Does it get compiled when the first user (or tens-hundreds of concurrent users) request the page after a deploy

Or could it be added to the heroku_install script after `bower install`?

**Comment by seanpdoyle** [comment]
@nruth currently, the assets will be compiled at deploy time by running along with [`rake assets:precompile`](https://github.com/thoughtbot/ember-cli-rails/blob/b70fe1a6b422d782ac8068fa96164467792f5a6f/lib/tasks/ember-cli.rake#L19-L24)

**Comment by nruth** [comment]
Thanks for clarifying! I'll try to add something brief to the readme.
