### ISSUE TITLE
https assets

### ISSUE THREAD

**Issue by sebyx07** [thoughtbot/ember-cli-rails#415]
the ```include_ember_stylesheet_tags``` and ```include_ember_script_tags``` use https in production mode.How can i disable this behavior?

**Comment by seanpdoyle** [comment]
Are you using [`force_ssl = true`](http://api.rubyonrails.org/classes/ActionController/ForceSSL/ClassMethods.html) in your controlller or in `config/environments/production.rb`?

Are you prepending a prefix with `https` as part of your `ember-cli-build.js` build/deploy process?

Closing this issue, as it seems unrelated to this gem.
