### ISSUE TITLE
rake ember:compile returns 0 exit code even with failed compilation

### ISSUE THREAD

**Issue by wireframe** [thoughtbot/ember-cli-rails#417]
compiling the app via rake appears like everything is fine, but grepping my `log/ember-appname.development.log` log file is littered with error messages like this:

```
Package: json-stable-stringify
Required by: frontend / broccoli-asset-rev
  * Specified: 1.0.1
  * Installed: (not installed)
```

```bash
$ rake ember:compile && echo $?
$ 0
```

raising an error with a truncated (or full) error from the shell/log would be *hugely* helpful.

**Comment by seanpdoyle** [comment]
@wireframe thanks, this is certainly a bug.

I'll look into it.

**Comment by seanpdoyle** [comment]
@wireframe on further inspection, things might be behaving properly.

The [`ember:compile` Rake task depends on `ember:install`](https://github.com/thoughtbot/ember-cli-rails/blob/b70fe1a6b422d782ac8068fa96164467792f5a6f/lib/tasks/ember-cli.rake#L3), which would install the missing dependencies. 

Other than the logs containing output about missing dependencies (which might come from [`ember-cli-dependency-checker`](https://github.com/quaertym/ember-cli-dependency-checker/blob/6a3d4d11da15921e95376e2d2431fa9ed23b971e/lib/reporter.js#L34-L35)), what behavior are you seeing that indicates that the build is failing?

**Comment by wireframe** [comment]
after running `rake ember:compile` with the failed state, I reload my rails app and get an error from the ember controller saying that the index.html file can not be found.

**Comment by seanpdoyle** [comment]
@wireframe I've tried to reproduce your issues with https://github.com/seanpdoyle/ember-cli-rails-heroku-example, but I'm having some trouble. The `ember:install` Rake dependency seems to be preventing me from compiling without a necessary dependency.

Could you pull https://github.com/seanpdoyle/ember-cli-rails-heroku-example down and try to reproduce? If you're able to, could you share the steps it took on this issue?

**Comment by klaustopher** [comment]
I just ran into an issue as well ... I had an issue on one machine, that `~/.config/configstore/ember-cli.json` was owned by root and ember-cli could not change it.

```
$ RAILS_ENV=staging bin/rake ember:compile
$ echo $?
0
```

The command finishes successfully, but the app is not available and if I look into the log file, this:

```
$ cat log/ember-demandcheck.staging.log
/srv/www/app/releases/20160317152940/demandcheck/node_modules/ember-cli/node_modules/configstore/index.js:53
				throw err;
				      ^
Error: EACCES, permission denied '/home/deploy/.config/configstore/ember-cli.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.create.all.get (/srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/node_modules/configstore/index.js:27:44)
    at clientId (/srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/lib/cli/index.js:22:21)
    at module.exports (/srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/lib/cli/index.js:65:19)
    at /srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/bin/ember:26:3
    at /srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/node_modules/resolve/lib/async.js:44:21
    at ondir (/srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/node_modules/resolve/lib/async.js:187:31)
    at /srv/www/optisure_staging/releases/20160317152940/demandcheck/node_modules/ember-cli/node_modules/resolve/lib/async.js:153:39
```

This is particularly annoying if this happens in `assets:precompile` because it gets totally hidden and we only see that the app is not there because our customers are seeing 500s.

**Comment by klaustopher** [comment]
As a side note ... If i.e. `bower-github.yml` is not writable, the `ember:install` fails with all bells and whistles :smile: 

```
$ RAILS_ENV=staging bin/rake ember:compile --trace
** Invoke ember:compile (first_time)
** Invoke ember:install (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute ember:install
          ERROR: Failed command: `/usr/local/bin/bower prune && /usr/local/bin/bower install`
          OUTPUT:

Error: EACCES, permission denied '/home/deploy/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:432:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:286:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by seanpdoyle** [comment]
@klaustopher thanks for the additional information.

> `~/.config/configstore/ember-cli.json` was owned by root and ember-cli could not change it.

> Error: EACCES, permission denied '/home/deploy/.config/configstore/bower-github.yml'
You don't have access to this file.

I'm not familiar with either of those files or the directory they're located in. Could you explain their significance, and maybe link to some documentation about them?

**Comment by klaustopher** [comment]
ehrm, I have no idea what they are for exactly ... I think it might have something to do with this: https://www.npmjs.com/package/configstore

But the problem is, not with this file exactly. The problem is, that an error happens during `rake ember:compile` but the command still finishes with a success state

**Comment by seanpdoyle** [comment]
@klaustopher @wireframe using https://github.com/seanpdoyle/ember-cli-rails-heroku-example as a base application, I've done some digging and extracted the shell command that `ember-cli-rails` will generate for a given application.

Running it (with `tee`):

```bash
~/src/ember-cli-rails-heroku-example/frontend master
❯ /Users/seanpdoyle/src/ember-cli-rails-heroku-example/frontend/node_modules/.bin/ember build --environment 'development' --output-path '/Users/seanpdoyle/src/ember-cli-rails-heroku-example/tmp/ember-cli/apps/frontend' | /usr/bin/tee -a '/Users/seanpdoyle/src/ember-cli-rails-heroku-example/log/ember-frontend.development.log'

Missing npm packages: 
Package: ember-data
  * Specified: 1.13.15
  * Installed: (not installed)

Run `npm install` to install missing dependencies.


~/src/ember-cli-rails-heroku-example/frontend master
❯ echo $?
0
```

Without the call to `tee`:

```bash
~/src/ember-cli-rails-heroku-example/frontend master
❯ /Users/seanpdoyle/src/ember-cli-rails-heroku-example/frontend/node_modules/.bin/ember build --environment 'development' --output-path '/Users/seanpdoyle/src/ember-cli-rails-heroku-example/tmp/ember-cli/apps/frontend'                                                                                                           

Missing npm packages: 
Package: ember-data
  * Specified: 1.13.15
  * Installed: (not installed)

Run `npm install` to install missing dependencies.


~/src/ember-cli-rails-heroku-example/frontend master
❯ echo $?
1
```

It looks like piping the output to `tee` is hiding the exit status of the initial command.

I'll investigate further.

**Comment by seanpdoyle** [comment]
@thoughtbot/shell can anyone help with https://github.com/thoughtbot/ember-cli-rails/issues/417#issuecomment-197991094?

**Comment by klaustopher** [comment]
The strange thing is, that `ember:compile` does fail and `ember:install` does not ... Are they handled differently?

**Comment by seanpdoyle** [comment]
Using `set -o pipefail` corrects it:

```bash
~/src/ember-cli-rails-heroku-example/frontend master
❯ set -o pipefail; /Users/seanpdoyle/src/ember-cli-rails-heroku-example/frontend/node_modules/.bin/ember build --environment 'development' --output-path '/Users/seanpdoyle/src/ember-cli-rails-heroku-example/tmp/ember-cli/apps/frontend' | /usr/bin/tee -a '/Users/seanpdoyle/src/ember-cli-rails-heroku-example/log/ember-frontend.development.log'

Missing npm packages: 
Package: ember-data
  * Specified: 1.13.15
  * Installed: (not installed)

Run `npm install` to install missing dependencies.


~/src/ember-cli-rails-heroku-example/frontend master
❯ echo $?
1
```

**Comment by seanpdoyle** [comment]
@klaustopher they're not "handled" different, in that they're both generated by [EmberCli::Command](https://github.com/thoughtbot/ember-cli-rails/blob/master/lib/ember_cli/command.rb) and run through [EmberCli::Runner](https://github.com/thoughtbot/ember-cli-rails/blob/master/lib/ember_cli/runner.rb), but they're different commands.

**Comment by klaustopher** [comment]
Then it's really, really strange, that they handle failures differently, I'll take a look tomorrow morning, workday is over ;)

**Comment by klaustopher** [comment]
Looking at https://github.com/thoughtbot/ember-cli-rails/blob/master/lib/ember_cli/shell.rb#L44, the install commands are executed directly by the runner, whereas the compile step (https://github.com/thoughtbot/ember-cli-rails/blob/master/lib/ember_cli/shell.rb#L17) is run by an `EmberCli::Command`

**Comment by seanpdoyle** [comment]
@wireframe @klaustopher could you try the [`set-pipefail`](https://github.com/thoughtbot/ember-cli-rails/pull/418) branch?

**Comment by klaustopher** [comment]
## version 0.7.2

```
$ ls -lah ~/.config/configstore/ember-cli.json
-rw------- 1 root wheel 56 Mär 17 14:14 /Users/klaustopher/.config/configstore/ember-cli.json

$ bundle show ember-cli-rails
/Users/klaustopher/.rvm/gems/ruby-2.2.2/gems/ember-cli-rails-0.7.2

$ bin/rake ember:compile
$

```


~~~

## set-pipefail branch:

```
$ ls -lah ~/.config/configstore/ember-cli.json
-rw------- 1 root wheel 56 Mär 17 14:14 /Users/klaustopher/.config/configstore/ember-cli.json

$ bundle show ember-cli-rails
/Users/klaustopher/.rvm/gems/ruby-2.2.2/bundler/gems/ember-cli-rails-06020e015d4d

$ bin/rake ember:compile
          ERROR: Failed command: `set -o pipefail; /Users/klaustopher/Projects/Clark/application/feed/node_modules/ember-cli/bin/ember build --environment 'development' --output-path '/Users/klaustopher/Projects/Clark/application/tmp/ember-cli/apps/feed' | /usr/bin/tee -a '/Users/klaustopher/Projects/Clark/application/log/ember-feed.development.log'`
          OUTPUT:
            /Users/klaustopher/Projects/Clark/application/feed/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/Users/klaustopher/.config/configstore/ember-cli.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/Users/klaustopher/Projects/Clark/application/feed/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/Users/klaustopher/Projects/Clark/application/feed/node_modules/configstore/index.js:27:44)
    at clientId (/Users/klaustopher/Projects/Clark/application/feed/node_modules/ember-cli/lib/cli/index.js:22:21)
    at module.exports (/Users/klaustopher/Projects/Clark/application/feed/node_modules/ember-cli/lib/cli/index.js:65:19)
    at /Users/klaustopher/Projects/Clark/application/feed/node_modules/ember-cli/bin/ember:26:3
    at /Users/klaustopher/Projects/Clark/application/feed/node_modules/resolve/lib/async.js:44:21
    at ondir (/Users/klaustopher/Projects/Clark/application/feed/node_modules/resolve/lib/async.js:187:31)
```

Looks good to me! :+1: 

I cannot test on an ubuntu machine before tomorrow morning, but I just tested that  `set -o pipefail` is also available on our machines. Just a quick glance through the net told me that the option *might* not be available under [dash](https://wiki.ubuntu.com/DashAsBinSh). So I will check tomorrow if this works on a vanilla ubuntu machine.

**Comment by seanpdoyle** [comment]
@wireframe @klaustopher could you try the latest version of the (now poorly named)  [`set-pipefail`](https://github.com/thoughtbot/ember-cli-rails/pull/418) branch?

It uses an alternative (hopefully cross platform) solution.

**Comment by klaustopher** [comment]
see comment in the PR, it fails again :/

**Comment by seanpdoyle** [comment]
@klaustopher @wireframe could you try out the [`remove-tee`](https://github.com/thoughtbot/ember-cli-rails/pull/420) branch instead:

```rb
# Gemfile

gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails", branch: "remove-tee"
```
