### ISSUE TITLE
0.7.3 release/pre-release?

### ISSUE THREAD

**Issue by wireframe** [thoughtbot/ember-cli-rails#426]
any chance of getting a rubygem packaged with the latest changes to help kick the tires?  any other changes needed for the next release?

**Comment by seanpdoyle** [comment]
a `0.7.3` or `0.8.0` release is currently blocked by https://github.com/thoughtbot/ember-cli-rails/pull/423.

If you'd like to try a "pre-release", you can use `master`, or the https://github.com/thoughtbot/ember-cli-rails/commit/ef6e96398059d55c4917faff7f7578c6d2c9f116 commit specifically.

**Comment by seanpdoyle** [comment]
[`0.7.3` released](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.7.3).
