### ISSUE TITLE
ember install error: Errno::ENOENT: No such file or directory - chdir

### ISSUE THREAD

**Issue by LingboTang** [thoughtbot/ember-cli-rails#428]
I got this error when I run `rake ember:install` followed by the tutorial.
The following code is how I set my ember.rb:
```
EmberCli.configure do |c|
  c.app :itemtracking
  c.app :frontend,
    path: "~/item_tracking/client/dist"
end

``` 
And how I set the routes.rb is the same as the tutorial.
I'm sure the path is correct and I built the ember app in the path before I installed ember-cli-rails.
What could be the problem?

**Comment by seanpdoyle** [comment]
@LingboTang thanks for opening this issue!

> `c.app :frontend, path: "~/item_tracking/client/dist"`

> I built the ember app in the path before I installed ember-cli-rails.

Could you explain your use case? 

Why are you building the ember app outside of `ember-cli-rails`?

Is `c.app :itemtracking` your ember application? Does it exist in `Rails.root.join("itemtracking")`?

Mentioning your `~/` directory could be a bad idea -- have you tried using a relative path?

What is the significance of pointing to the `/dist` directory?

Assuming your Rails project exists in a `item_tracking` directory and your Ember application exists in the `client` directory, the following would be a proper configuration:

```rb
EmberCli.configure do |c|
  c.app :client
end
```

**Comment by LingboTang** [comment]
I developed my web app frontend in item_tracking/client with ember, and backend in item_tracking/server with ruby on rails, their communication is done by jsonAPI currently. I wanted to use ember-cli-rails to deploy my app, so I built the ember production first, trying to serve the index.html by rails server.

**Comment by LingboTang** [comment]
Now I changed it to:
```
EmberCli.configure do |c|
  c.app :client
  c.app :frontend, path: "/item_tracking/client"
end
```

But I still got the error

**Comment by seanpdoyle** [comment]
> I developed my web app frontend in item_tracking/client with ember, and backend in item_tracking/server with ruby on rails

Given this directory structure, try this configuration:

```rb
EmberCli.configure do |c|
  c.app :frontend, path: "../client"
end
```

> I wanted to use ember-cli-rails to deploy my app, so I built the ember production first, trying to serve the index.html by rails server.

This goes against the utility of the `ember-cli-rails` library.

The idea here is that `ember-cli-rails` is responsible for communicating with and managing your Ember application.

Given your `server` and `client` directory structure, I'm assuming you aren't deploying to Heroku.

I recommend you consider integrating with [ember-cli-deploy](http://www.ember-cli-deploy.com/)'s ["Lightning" deploy strategy](http://ember-cli.com/ember-cli-deploy/docs/v0.6.x/the-lightning-strategy/) via the [ember-cli-rails-deploy-redis](https://github.com/seanpdoyle/ember-cli-rails-deploy-redis) deployment strategy.

**Comment by seanpdoyle** [comment]
I'm closing this issue, since it stems from configuring an invalid `path` value .

**Comment by LingboTang** [comment]
That works, thank you
