### ISSUE TITLE
Can't view ember-cli application in "/"

### ISSUE THREAD

**Issue by LingboTang** [thoughtbot/ember-cli-rails#430]
I mounted my ember app to "/" as the guideline:

```
Rails.application.routes.draw do
  mount_ember_app :frontend, to: "/"
end
```
and `rake ember:install` is running without problem: 
```
version: 2.2.0-beta.6
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 4.4.1
npm: 2.14.10
os: linux x64
```
but when I navigate to "/" I can't see anything.

**Comment by seanpdoyle** [comment]
@LingboTang thanks for opening this issue!

> but when I navigate to "/" I can't see anything.

Are you [overriding the view](https://github.com/thoughtbot/ember-cli-rails#overriding-the-view)?

What about [overriding the controller](https://github.com/thoughtbot/ember-cli-rails#overriding-the-controller)?

If not, are there errors on the server?

What about errors in your browser about missing assets?

**Comment by LingboTang** [comment]
When I run `rails s -e production`
I got:
```
ActionView::Template::Error (Failed to find assets matching `(?-mix:client(.*)\.js\z)`):
    1: <%= include_ember_script_tags :frontend %>
    2: <%= include_ember_stylesheet_tags :frontend %>
    3: <%= render_ember_app :frontend do |head, body| %>
    4:   <% head.append do %>
  app/views/ember_cli/ember/index.html.erb:1:in
`_app_views_ember_cli_ember_index_html_erb___3995453350200719983_70267274045520'
```

**Comment by seanpdoyle** [comment]
> ` (Failed to find assets matching `(?-mix:client(.*)\.js\z)`)`

Where did this regex come from?

@LingboTang could you please provide some more context around how you have the gem configured for your project?

**Comment by seanpdoyle** [comment]
Closing this issue for now.

@LingboTang if you're still experiencing this issue, please respond to https://github.com/thoughtbot/ember-cli-rails/issues/430#issuecomment-207441113 and I'll reopen.

**Comment by afomi** [comment]
I was battling this for a couple days. `(Failed to find assets matching(?-mix:frontned(.*).js\z))`

After upgrading Rails from `4.2.5` to `4.2.8`, the issue disappeared for me.
