### ISSUE TITLE
Helpers don't respect asset_host or digest config

### ISSUE THREAD

**Issue by henrymazza** [thoughtbot/ember-cli-rails#431]
I’m using `ember deploy` to push the javascript to S3, but I need to serve it via a Rails template like: 

```erb
<%= render_ember_app :frontend do |head, body| %>
...
<% end %>
```
but the only links it outputs, even in production, are: 

```erb
  ...
  <script src="assets/vendor.js"></script>
  <script src="assets/frontend.js"></script>
  ...
```

How to make ember-cli-rails respect my asset_host and fingerprinting settings? I was able to force it with the <base> tag, but no luck with fingerprinting.

**Comment by seanpdoyle** [comment]
>  respect my asset_host and fingerprinting settings

Do you mean your Rails configurations or your EmberCLI configurations?

> I’m using `ember deploy` to push the javascript to S3

What is your ember-cli-deployment strategy?

How does that strategy serve the `index.html`?

If you're using the [Lightning Deploy Strategy](http://ember-cli.com/ember-cli-deploy/docs/v0.6.x/the-lightning-strategy/), checkout the [ember-cli-rails-deploy-redis](https://github.com/seanpdoyle/ember-cli-rails-deploy-redis) gem.

**Comment by henrymazza** [comment]
My deploy strategy is building ember and uploading to S3 (not that complex).

The stylesheets are shared between Rails and Ember, that’s the initial reason I started to use ember-cli-rails and that’s why the `index.html` is served by Rails. Another problem is I can’t build ember on server, nodejs is just too slow and too big. Every deploy the system stutters. So it had to work:
```erb
<base href=“http://s3_bucket_address”>
<%= include_ember_script_tags :frontend %>
<base href=“http://my_rails_server_address”>
<%= stylesheet_link_tag "application" %>
```
My main difficulty is these shared CSSs, I don’t think any deploy strategy can deal with a chasm on the assets. Anyway I can disable fingerprinting for Ember and call it a day, but I thought __the helpers should work like Rails’s helpers (asset_host + fingerprinting)__.

PS: I’ll see if the Lightning Strategy can work.

**Comment by henrymazza** [comment]
Lightning really worth it, thanks for the tip.
