### ISSUE TITLE
How to work with CSS/SASS?

### ISSUE THREAD

**Issue by andrewhavens** [thoughtbot/ember-cli-rails#434]
I am setting up my ember-cli app with the SASS plugin and am running into an issue regarding the assets directory. The Rails assets path is overriding the ember-cli assets path. I noticed that the readme does not mention how you are supposed to handle CSS assets. Are they meant to be managed in the Rails app or the Ember app?

**Comment by seanpdoyle** [comment]
Thanks for opening this issue, @andrewhavens.

Technically, you can keep your CSS and SCSS anywhere you'd like: in your server code or in your Ember client code. 

If you'd like to have styles from each, you could [override the view](https://github.com/thoughtbot/ember-cli-rails#overriding-the-view):

```erb
<%= render_ember_app :frontend do |head| %>
  <% head.append do %>
    <%= stylesheet_link_tag "my-rails-generated-styles" %>
    <%= csrf_meta_tags %>
  <% end %>
<% end %>
```

This snippet demonstrates injecting a `<link>` tag from your server into your EmberCLI-generated `index.html`.

There is nothing technically limiting the sharing of CSS code between your client and your server, although picking one or the other might make sense from an organizational perspective.

The only thing that **isn't** currently possible is sharing SCSS code. 

Serving the already compiled CSS is no issue, but you can't share and precompile SCSS code that is split between repositories.

**Comment by andrewhavens** [comment]
Thanks for the response @seanpdoyle. Not sure what I did, but all of a sudden, my SASS code started working in my Ember app. 👻
