### ISSUE TITLE
Rake assets:precompile not building ember assets (vendor.js, etc.)

### ISSUE THREAD

**Issue by coreypmurphy** [thoughtbot/ember-cli-rails#440]
I have a rails 4 app using an ember frontend.

When running ```rake assets:precompile RAILS_ENV=production``` the rails assets are compiled and put into the rails root public folder but the corresponding "ember build" that's supposed to occur, seems to be failing silently.  There aren't any fingerprinted "vendor.js" or other ember built assets that show up in the public folder, or anywhere else for that matter.  If I cd into my "frontend" folder (which is where our ember app lives) and run ```ember build``` or ```ember build --prod``` then the dist folder is populated with the compiled ember assets appropriately, but again, nothing is copied or moved into the public folder or any other folder.

My impression from the docs is that running ```rake assets:precompile``` should compile my ember assets and place them (or just the index.html) into the rails root public folder for deployment.  Am I incorrect in this line of thought?  If those files/assets aren't copied into that directory before I deploy with capistrano, then the app fails to load on the server.  Should the files in "dist" be placed into "frontend/public" instead? And if so, shouldn't ember-cli-rails do this for me when doing a "build" or precompile for deploy?

(**Note:** I have to precompile the ember assets prior to deployment because our server doesn't have a javascript runtime.)

So to summarize, "ember build" works fine when manually invoked in our frontend folder and outputs compiled assets into "dist".  Any of the rake tasks (ember:compile, assets:precompile) don't compile anything and don't provide any error.  Lastly, even when assets get compiled if they aren't manually moved into public the app doesn't run.

Before upgrading to version 0.7.2 of ember-cli-rails, we were able to run ```rake assets:precompile``` and the ember stuff would build into our rails root public folder.  That "working" version however was 0.3.5.  Ouch.  So what am I missing?

The app works great running in development (localhost) as well as test.

Any help is greatly appreciated!

Which operating system and version is the project developed on? 
OSX 10.10.5

Which version of [`ruby`][ruby] is the project developed on?
2.2.2p95

Which version of [`npm`][npm] is the project developed on? 
3.8.6

Which version of [`ember-cli`][ember-cli] is the project developed on?
2.4.2

What is the [`rails`][rails] version?
4.2.4

What is the [`ember-cli-rails`][gem] version (from `Gemfile`)?
0.7.3

What is the [`ember-cli-rails-addon`][addon] version (from `package.json`)?
0.7.0

What are the contents of `config/initializers/ember.rb`?
```
EmberCLI.configure do |c|
  c.app :frontend, path: Rails.root.join("frontend")
end
```

What are the contents of the Rails' view that renders the Ember application?
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CoursebuilderFrontend</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {{content-for "head"}}
    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/coursebuilder-frontend.css">
    {{content-for "head-footer"}}
  </head>
  <body>
    {{content-for "body"}}
    <script src="assets/vendor.js"></script>
    <script src="assets/coursebuilder-frontend.js"></script>
    {{content-for "body-footer"}}
  </body>
</html>
```

How are the EmberCLI-related routes defined?
not sure how to answer. baseURL?, router.js?

How is the application deployed?
asset precompile locally, deployed via capistrano to unix/apache setup (server has no javascript runtime)

**Comment by seanpdoyle** [comment]
@coreypmurphy thanks for opening this issue, and thanks for providing so much information!

I'll process the issue bit by bit, starting with:

> My impression from the docs is that running rake assets:precompile should compile my ember assets and place them (or just the `index.html`) into the rails root public folder for deployment. Am I incorrect in this line of thought?

This is not the case. The `mount_ember_app` helper handles:

* mounting the Rails-style `ember_cli/ember#index` action, mapping `GET` requests for `.html` files to the specified endpoint to the `EmberCli::Controller`, which is responsible for serving the EmberCLI-generated `index.html`. This `index.html` file contains `<link>` and `<script>` (and possibly `<img>`) tags that refer to other EmberCLI-generated assets. These assets are served by...
* mounting the EmberCLI-generated assets via a [Rack::File](https://github.com/thoughtbot/ember-cli-rails/blob/a97145d1ed372a7cd7aad3e44f4c613cb350de69/lib/ember_cli/deploy/file.rb#L15-L17) app.

In combination, these two route helpers and their Rack counterparts handle serving both the `index.html` file and the assets it depends on.

**Comment by seanpdoyle** [comment]
> Before upgrading to version 0.7.2 of ember-cli-rails, we were able to run rake assets:precompile and the ember stuff would build into our rails root public folder.

This was a side effect of processing Ember assets through Rails' asset pipeline. We have [removed the Sprockets dependency](https://github.com/thoughtbot/ember-cli-rails/commit/ffb7c2d71f443d993d39a474a9517c318ddd4508) in favor of letting EmberCLI manage it's own assets. 

This decision has freed us from keeping the project up to date with EmberCLI's asset-processing methods, and gives EmberCLI ownership over the front-end.

**Comment by seanpdoyle** [comment]
> What are the contents of the Rails' view that renders the Ember application?
> ...

I'm guessing that the snippet you shared is not the contents of the Rails view, but is instead contents of `frontend/index.html`.

This leads me to believe that you [have not overridden the Rails view][override]. Is that assumption correct?

[override]: https://github.com/thoughtbot/ember-cli-rails#overriding-the-view

**Comment by seanpdoyle** [comment]
>  If those files/assets aren't copied into that directory before I deploy with capistrano, then the app fails to load on the server

Have you read the [Capistrano](https://github.com/thoughtbot/ember-cli-rails#capistrano) block of the Deployment section of the README?

Are you able to install the necessary JavaScript runtimes on your deployment machines?

If not, we recommend using [ember-cli-deploy](http://ember-cli-deploy.github.io/ember-cli-deploy/) to deploy your front-end asses.

We recommend deploying combining the [ember-cli-deploy Lightning Deploy Strategy](http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/the-lightning-strategy/) with the [ember-cli-rails-deploy-redis](https://github.com/seanpdoyle/ember-cli-rails-deploy-redis) Deployment Strategy.

**Comment by coreypmurphy** [comment]
> This leads me to believe that you have not overridden the Rails view. Is that assumption correct?

Correct, we have not.  In our rails routes.rb file we are using "mount_ember_app" as such:
```mount_ember_app :frontend, to: "/"```

**Comment by coreypmurphy** [comment]
>Are you able to install the necessary JavaScript runtimes on your deployment machines?
No - this project is in a large corporate giant where open source stuff is more or less shunned.  We're a small pocket making our way with RoR and Ember.  We try not to ask for too much as it draws unwanted attention our way.

> Have you read the Capistrano block of the Deployment section of the README?
Yes - and Capistrano is our deployment strategy of choice however the docs again reference how EmberCLI's compilation triggers "rake assets:precompile" which then runs npm and bower installs but we can't have any of that happening on our server since it lacks a JavaScript runtime.  And that brings us to the crux of our problem: we need to precompile everything locally at the beginning of, or before a deploy, such that what gets deployed is ready to go and doesn't require any fancy footwork on the server.

I'll look over the ember-cli-deploy and ember-cli-rails-deploy-redis approach and see what we can come up with.

I appreciate all the explanation you've provided thus far!  Once I fully understand the mechanics and overall flow of things, solving this will become apparent but at the moment, it's all still fuzzy as to what's supposed to happen and when.  Having the "side effect" of it all happening during the assets precompile was nice but letting Ember manage the frontend and Rails the backend made the most long term sense.

**Comment by coreypmurphy** [comment]
@rondale-sc was actually on site with us when we did the big upgrade to ember 2.4.2 and he said he had concerns regarding how we'd be deploying going forward but didn't have enough time with us to work out the details.  He's been trying to help out with this, but he has a day job like everyone else. ;)

**Comment by coreypmurphy** [comment]
@seanpdoyle, just so I'm clear about something . . . 

> This is not the case. The mount_ember_app helper handles:
> 
> mounting the Rails-style ember_cli/ember#index action, mapping GET requests for .html files to the specified endpoint to the EmberCli::Controller, which is responsible for serving the EmberCLI-generated index.html. This index.html file contains "link" and "script" (and possibly "img") tags that refer to other EmberCLI-generated assets. These assets are served by...
> mounting the EmberCLI-generated assets via a Rack::File app.
> In combination, these two route helpers and their Rack counterparts handle serving both the index.html file and the assets it depends on.

So where does the "index.html" that EmberCli relies on need to live in a deployed app so that the EmberCli::Controller can find it?  The rails "public" folder?  Could I just symlink the contents of the dist folder to public?

We're not quite ready to separate and deploy our backend separately from our frontend as seems to be the path most are moving.

**Comment by coreypmurphy** [comment]
We could use ember-cli-deploy and ember-cli-deploy-build however there doesn't seem to be a community built plugin to incorporate for doing what we're trying to do.  Precompiling locally and deploying via Capistrano as a whole backend/frontend application seems straightforward to me but understanding where the compiled ember assets need to live in the deployed app is the piece I'm not fully understanding.  Having this answered would help alot and I will be happy to close the issue.

Thanks again for all the help!

**Comment by coreypmurphy** [comment]
So is there a flag or option that allows for local asset precompilation?

**Comment by coreypmurphy** [comment]
Ended up using a part of the suggestion that @pwim used in issue#427.

```
# config/intializers/ember.rb
if Rails.env.production? || Rails.env.staging?
  EmberCli.instance_variable_set(:@root, Rails.root.join("public/").tap(&:mkpath))
end

EmberCLI.configure do |c|
  c.app :frontend, path: Rails.root.join("frontend")
end
```

I have a rake task that does a production build, copies the contents of "dist" to the "/public/apps/frontend/" folder.  Do some git stuff, and then deploy using Capistrano.

EmberCli is now happy since "@root" is pointing at our "production" built "index.html" and dev continues to use the default EmberCli pathing (/tmp/ember-cli/app/#{app_name}).

This may not be as elegant as separating our backend and frontend apps and the "build and deploy" isn't as fast as some of the other approaches such as "redis" but for our infrastructure, it's just fine and we don't have to leverage the ember-cli-deploy addon or any other plugins.

I appreciate all the help and the great work on this gem.  Thanks Sean and Jonathan!
