### ISSUE TITLE
Why this project is limited to ruby 2.1.0?

### ISSUE THREAD

**Issue by ipepe** [thoughtbot/ember-cli-rails#441]
Because it seems like You could easily achieve 2.0.0 (well doing it myself took me less than 30 minutes). But seems like You just want to make people fork Your projects...

**Comment by seanpdoyle** [comment]
As of [February 24, 2016](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), Ruby `2.0.x` has been end-of-lifed.

For the sake of simplifying the maintenance of this project, we aim to support versions of Ruby that are themselves supported.

**Comment by ipepe** [comment]
For anyone who doesn't live in the future I recommend:
```ruby
gem "ember-cli-rails", git: 'https://github.com/ipepe/ember-cli-rails.git'
gem "ember-cli-rails-assets", git: 'https://github.com/ipepe/ember-cli-rails-assets.git'
gem "html_page", git: "https://github.com/ipepe/html_page.git"
```
and for package.json:
```json
{    "ember-cli-rails-addon": "~0.7.0" }
```
