### ISSUE TITLE
Support for JSON API spec? 

### ISSUE THREAD

**Issue by philpee2** [thoughtbot/ember-cli-rails#447]
New Ember projects use `JSONAPIAdapter` by default and expect API responses to match the [JSON API spec](http://jsonapi.org/). But getting Rails to serialize models according to this format is pretty hard. 

I always find this to be a pain point when starting new Ember/Rails projects. I've settled on using [ActiveModelAdapter](https://github.com/ember-data/active-model-adapter) and [ActiveModelSerializer](https://github.com/rails-api/active_model_serializers) instead, and I put together a [boilerplate](https://github.com/philpee2/ember-cli-rails-starter) to make that a little easier. 

However, boilerplates are a bad solution. I would much prefer it if using ember-cli-rails just worked out of the box, or came with a very easy configuration step to make it work, so that Rails and Ember can communicate with each other properly.

**Comment by seanpdoyle** [comment]
@philpee2 thanks for opening this issue and getting the discussion started.

This gem's main concern is integrating EmberCLI and Rails at the server/build level.

While I agree with your proposal in spirit, I think integration between Ember-Data and a Rails-based JSONAPI server is out of scope for this project.

However, I'd love to look over your proposed solution. If you'd like, please open a PR. Based on your implementation, we can decide what to do with the code.
