### ISSUE TITLE
'assets/vendor.js' and 'assets/vendor.css' are not found (variation of #120)

### ISSUE THREAD

**Issue by jaredgalanis** [thoughtbot/ember-cli-rails#450]
I am having the same issues as others in #120 and #438 . My ember app appears to build successfully and then fails on loading the vendor.css, vendor.js, frontend.css and frontend.js files.  I have tried increasing the build time and this does not resolve the issue.

```
Started GET "/assets/vendor.css" for ::1 at 2016-05-17 10:53:38 -0400
  
ActionController::RoutingError (No route matches [GET] "/assets/vendor.css")
```   

**Which operating system and version is the project developed on?**

OS X 10.11.4 (15E65)

**Which version of [`ruby`][ruby] is the project developed on?**

2.3.0

**Which version of [`npm`][npm] is the project developed on?**

3.3.12

**Which version of [`ember-cli`][ember-cli] is the project developed on?**

"ember-cli": "2.5.0"

**What is the [`rails`][rails] version?**

Rails 5.0.0.beta4

**What is the [`ember-cli-rails`][gem] version (from `Gemfile`)?**

ember-cli-rails (0.7.3)

**What is the [`ember-cli-rails-addon`][addon] version (from `package.json`)?**

"ember-cli-rails-addon": "0.7.0"

**Is your application server [multi-threaded][] (such as `puma` and `unicorn`) or is
it multi-process (such as thin and webrick)?**

Puma Version 3.3.0

**What are the contents of `config/initializers/ember.rb`?**

```
EmberCli.configure do |c|
  c.app :frontend,
  build_timeout: 25
end

```

**What are the contents of the Rails' view that renders the Ember application?**

I don't have a view override set up at this time.

**How are the EmberCLI-related routes defined?**

mount_ember_app :frontend, to: "/frontend"

**How is the application deployed?**
heroku

[ruby]: https://www.ruby-lang.org/
[node]: https://nodejs.org/en/
[npm]: https://www.npmjs.com/
[ember-cli]: http://ember-cli.com/
[rails]: https://github.com/rails/rails
[gem]: https://github.com/thoughtbot/ember-cli-rails
[addon]: https://github.com/rondale-sc/ember-cli-rails-addon/
[multi-threaded]: https://github.com/thoughtbot/ember-cli-rails/commit/ef0a49546a8c2e5fb0a298ba455fba97289065a1

**Comment by jaredgalanis** [comment]
Also adding the vendor.css, vendor.js, frontend.css, frontend.js and vendor.map and frontend.map files to the assets folders in Rails does get past this issue, but I then get an error on:

`vendor.js:15018Uncaught UnrecognizedURLError: /frontend`

**Comment by jaredgalanis** [comment]
I changed my EmberCLI-related routes definition to:
`mount_ember_app :frontend, to: "/"`
and it solved that particular issue. I have not tried to get other routes working yet, but I will update if there any additional issues.

**Comment by seanpdoyle** [comment]
@jaredgalanis thanks for both opening this issue and working it out!

> I will update if there any additional issues.

Please do.

**Comment by jaredgalanis** [comment]
So I am able to get other ember routes working with the routes definition:
`mount_ember_app :frontend, to: "/"`
However, for my use case, the issue with this is that I would like to mount the ember app at some path other than "/" because I am integrating with an existing rails app, not replacing it entirely. Mounting to "/" will not allow me to go to any rails routes that I've already set up in the existing rails app.

**Comment by seanpdoyle** [comment]
@jaredgalanis have you followed along with [this section of the README](https://github.com/thoughtbot/ember-cli-rails#mounting-multiple-ember-applications)?

**Comment by jaredgalanis** [comment]
Thanks Sean! I had not been following that. I think the title of the section about multiple ember apps threw me off. Setting the base URL to the app's mount point solved the problem for me. I'm going to mark this closed! But do you happen to know if I can avoid using index.html on ember's side? I would like to serve the ember app inside of the rails layout ideally.

**Comment by jaredgalanis** [comment]
Nevermind, I see you guys have a gem for this purpose here: 
https://github.com/seanpdoyle/ember-cli-rails-assets
I understand that this behavior is deprecated, but what would be the work around here if I didn't want the look of the ember app to be different from the rails app? To build out an ember version of the rails layout?

**Comment by seanpdoyle** [comment]
> I would like to serve the ember app inside of the rails layout ideally, but I know the docs say that index.html being served from ember is a fully formed HTML document.

Injecting the Ember application's assets into a Rails layout is possible, but strongly discouraged:

https://github.com/thoughtbot/ember-cli-rails#rendering-the-embercli-generated-js-and-css

Instead, would you be able to achieve the same results by [sharing CSS across applications](https://github.com/thoughtbot/ember-cli-rails#serving-rails-generated-css)?

**Comment by jaredgalanis** [comment]
Got it, thanks Sean. I appreciate the quick responses!

**Comment by jaredgalanis** [comment]
Sean, backing up a little on this one, if I were going to sketch out injecting the Ember assets into a Rails layout, how do you determine where the assets will show up? Ideally each Ember template will be served inside the body of the Rails layout. Is that just a matter of placing the `include_ember_script_tags` and `include_ember_stylesheet_tags` in the body of the Rails layout?

**Comment by jaredgalanis** [comment]
Sean, if I'm revisiting this issue of whether to inject the Ember app's assets into a Rails layout. I have it working (the Ember app is injected at the appropriate place in the layout and the Ember app behaves as expected). However, doing this seems to wreak havoc on the javascript plugins that I have included in the Rails app. Is this something that can be easily fixed?

**Comment by jaredgalanis** [comment]
Opening new issue #453
