### ISSUE TITLE
injecting Ember assets into Rails layout causes javascript errors even when Ember app is not loaded

### ISSUE THREAD

**Issue by jaredgalanis** [thoughtbot/ember-cli-rails#453]
I'm revisiting (see #450) the issue of whether to inject the Ember app's assets into a Rails layout because there is a lot functionality in my layout in Rails that I actually would prefer to avoid rebuilding right now. I have the injection working (the Ember app is injected at the appropriate place in the layout and the Ember app behaves as expected). However, doing this seems to wreak havoc on the javascript plugins that I have included in the Rails app on the Rails only pages, where I wouldn't expect it to occur. Pretty much every plugin is firing this error:

`Uncaught TypeError: $(...).[some-JS-plugin-initialization-function] is not a function
`

Is this common? Something that can be easily fixed?

**Which operating system and version is the project developed on?**

OS X 10.11.4 (15E65)

**Which version of [`ruby`][ruby] is the project developed on?**

2.3.0

**Which version of [`npm`][npm] is the project developed on?**

3.3.12

**Which version of [`ember-cli`][ember-cli] is the project developed on?**

"ember-cli": "2.5.0"

**What is the [`rails`][rails] version?**

Rails 5.0.0.beta4

**What is the [`ember-cli-rails`][gem] version (from `Gemfile`)?**

ember-cli-rails (0.7.3)

**What is the [`ember-cli-rails-addon`][addon] version (from `package.json`)?**

"ember-cli-rails-addon": "0.7.0"

**Is your application server [multi-threaded][] (such as `puma` and `unicorn`) or is
it multi-process (such as thin and webrick)?**

Puma Version 3.3.0

**What are the contents of `config/initializers/ember.rb`?**

```
EmberCli.configure do |c|
  c.app :frontend,
  build_timeout: 25
end

```

**What are the contents of the Rails' view that renders the Ember application?**

I don't have a view override set up at this time.

**How are the EmberCLI-related routes defined?**

mount_ember_app :frontend, to: "/frontend"

**How is the application deployed?**
heroku

[ruby]: https://www.ruby-lang.org/
[node]: https://nodejs.org/en/
[npm]: https://www.npmjs.com/
[ember-cli]: http://ember-cli.com/
[rails]: https://github.com/rails/rails
[gem]: https://github.com/thoughtbot/ember-cli-rails
[addon]: https://github.com/rondale-sc/ember-cli-rails-addon/
[multi-threaded]: https://github.com/thoughtbot/ember-cli-rails/commit/ef0a49546a8c2e5fb0a298ba455fba97289065a1

**Comment by krasnoukhov** [comment]
This seems to be related to two different jQuery versions loading up. The first one comes from your asset pipeline along with all other 3rd party libraries initialized with it. The second one is from Ember's vendor.js, which obviously does not know about your plugins.

The solution that worked for me was adding something like this to `ember-cli-build.js`:

```javascript
/*jshint node:true*/
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // We use jQuery from asset pipeline in non-test envs
    vendorFiles: EmberApp.env() === 'test' ? {} : { 'jquery.js': false }
  });

  return app.toTree();
};
```

This basically will not bundle jQuery into Ember app anymore, so there's no second conflicting version. Let me know if that helps

**Comment by jaredgalanis** [comment]
Thanks so much @krasnoukhov, this work like a charm - you were totally right about the conflicting versions of jquery.
