### ISSUE TITLE
Ember cli rails breaks when deprecations(warnings) are found on Ember

### ISSUE THREAD

**Issue by victor95pc** [thoughtbot/ember-cli-rails#464]
Linux 64-bits, Manjaro(Arch Linux)
ruby 2.1.8
npm 3.9.5
ember-cli 2.6.2
rails 4.2.6
ember-cli-rails gem 0.7.4
ember-cli-rails-addon 0.7.0
application server webrick

```
#config/initializers/ember.rb
EmberCli.configure do |c|
  c.app :frontend
end
```

contents of the Rails' view
```
<%= render_ember_app :frontend do |head, body| %>
<% end %>
```
 route.rb
  ```
mount_ember_app    :frontend, to: '/cursos', controller: 'ember_loader'
mount_ember_assets :frontend, to: '/'
```

There is a problem on ember-cli-rails, every deprecation raise like a BuildError, which is not good, a deprecation example: 
`DEPRECATION: Overriding init without calling this._super is deprecated`

**Comment by victor95pc** [comment]
Pull Request: #465

**Comment by seanpdoyle** [comment]
@victor95pc https://github.com/thoughtbot/ember-cli-rails/pull/468 should address this.

Would you mind pulling down `master` and testing whether it has been resolved?

**Comment by victor95pc** [comment]
@seanpdoyle @mhaylock Thx guys for your work, sorry for the delay, this PR work perfect and cover all use cases.

**Comment by seanpdoyle** [comment]
@victor95pc thanks for clarifying!
