### ISSUE TITLE
Gem version 0.8 but addon still 0.7.1?

### ISSUE THREAD

**Issue by nruth** [thoughtbot/ember-cli-rails#477]
The readme says:

> Be sure that the addon's MAJOR and MINOR version matches the gem's MAJOR and MINOR versions.
> 
> For instance, if you're using the 0.6.x version of the gem, specify ~> 0.6.0 in your Ember app's package.json:

But the latest addon version https://github.com/rondale-sc/ember-cli-rails-addon is 0.7.1.
Are there breaking changes?

**Comment by vovimayhem** [comment]
Got the same problem...

**Comment by seanpdoyle** [comment]
Thanks for opening this issue!

Could you try again?

[This commit](https://github.com/rondale-sc/ember-cli-rails-addon/commit/095aae51751a57f541592b6a1a71f9269b3ac0a9) should resolve this issue.

**Comment by seanpdoyle** [comment]
Considering this closed, as [`ember-cli-rails-addon@0.8.0`](https://www.npmjs.com/package/ember-cli-rails-addon) was released on August 15th.

**Comment by nruth** [comment]
This is current again with the gem being 0.9 or 0.10 but the ember addon still 0.8. Is it something that can be written around in the readme or are the matching versions worth keeping & we just need a no-op version bump pr on the addon?

**Comment by seanpdoyle** [comment]
I've published [`0.10.0`](https://www.npmjs.com/package/ember-cli-rails-addon) to the NPM registry, along with some older versions.

Unfortunately, due to my incompetence with the `npm publish` and `npm unpublish command`, versions for `0.8.7` and `0.9.0` are missing and cannot be re-published.

**Comment by nruth** [comment]
Hey Sean, thanks for doing that.

I don't personally need 0.8.7 or 0.9.0 but I guess putting an 0.8.8 and 0.9.1 out (with no changes) could help people who wanted to pin to those. May not be worth the extra work though.
