### ISSUE TITLE
better tolerate long ember builds

### ISSUE THREAD

**Issue by jrr** [thoughtbot/ember-cli-rails#483]
I'm trying to use ember-cli-rails for local development and test, and hit a speed bump:
- It appears that ember-cli-rails builds the ember app lazily, the first time its route is visited.
- My ember app has a ~45 second build time (!).
- I'm running capybara/rspec feature tests, and find that the first one fails with a `Capybara::Poltergeist::StatusFailError` on its first `visit`.

Ideally, I'd like to wait for the ember build to complete before starting the first test. Any recommendations for how to configure this?

osx 10.11.6
ruby 2.3
npm 3.10.6, 
ember-cli 2.4.3
rails 5.0.0.beta3
ember-cli-rails 0.8.0
ember-cli-rails-addon 0.8.0
server `thin`, default configuration

`config/initializers/ember.rb`:
```
EmberCli.configure do |c|
    c.app :frontend, path: ENV['WEB_DIR']
end
```

**What are the contents of the Rails' view that renders the Ember application?**
```
<%= render_ember_app :frontend do |head| %>
  <% head.append do %>
    <%= csrf_meta_tags %>
  <% end %>
<% end %>
```

**How are the EmberCLI-related routes defined?**
`mount_ember_app :frontend, to: '/frontend', controller: 'ember', action: 'index'`

**Comment by jrr** [comment]
I managed to do it with a before hook:

```
config.before(:all, type: :feature) do
  EmberCli.compile!
end
```

Still might be something to consider as a configuration option, for those who have long builds or don't want the initial build to affect their reported test times.

**Comment by seanpdoyle** [comment]
Thank for bringing this to our attention @jrr, and double thanks for sharing your solution!

ember-cli-rails doesn't know anything about your testing framework, or testing in general.

On possible solution would be to compile the Ember app on Rails' server startup. 

Unfortunately, this would make running [there doesn't seem to be a Railtie hook for starting the server](http://api.rubyonrails.org/classes/Rails/Railtie/Configuration.html). This means that we'd have to compile the Ember application every time a `rails`, `rake`, `rspec`, etc process loads the application code. That would slow down the developer process substantially.

If your example code above resolves your issue, it's likely best to go with that.

**Comment by seanpdoyle** [comment]
https://github.com/ember-cli/ember-cli/issues would be a better place to discuss solutions to a 45 second build time than this project's issue tracker.

A 45 second build time is likely a symptom of a larger issue, either with the application, `ember-cli`'s build process, or a combination of both. Would you like to chat about working with thoughtbot to help reduce it?

**Comment by jrr** [comment]
Thanks for your input, Sean. I recognize that the build time is a problem, and will be addressing it separately in the future.

I'm happy with the before hook for now, so I'll close this.
