### ISSUE TITLE
Gzipped assets on Heroku

### ISSUE THREAD

**Issue by jdurand** [thoughtbot/ember-cli-rails#487]
I tried to gzip css & js assets with https://github.com/gdub22/ember-cli-gzip without success.
At best I was able to "gzip" the files with the `.css` and `.js` extensions but they are served without the `Content-Encoding:gzip` header that browsers seem to need in order to deliver the files properly.

Is there an easy `ember-cli-rails` config to achieve this?

Rails: 4.2.7.1
ember-cli-rails: 0.8.0
ember-cli-rails-addon: ~0.8.0
Deployment: Heroku

**Comment by plicjo** [comment]
I also have this issue.

**Comment by plicjo** [comment]
I was able to get Rails to server the gzipped assets with https://github.com/romanbsd/heroku-deflater

**Comment by jdurand** [comment]
I'm deploying my assets with CloudFront; I managed to go around this by ticking the "compress objects automatically" option in there.
