### ISSUE TITLE
How to set authentication fallback to ember page

### ISSUE THREAD

**Issue by sobinsunny** [thoughtbot/ember-cli-rails#516]
I am trying to access a rails app  with an url like [localhost:3000/v1/posts/1](url)>.

 If that user not authenticate it should redirect to login page(Ember page), But now its redirecting to devise login page(Rails view). how can setup this fallback.

I am using devise gem in rails
SimpleAuth in ember

**Comment by seanpdoyle** [comment]
Thanks for opening this issue.

Could you please provide more information by using the [ISSUE_TEMPLATE](https://github.com/thoughtbot/ember-cli-rails/blob/master/.github/ISSUE_TEMPLATE.md)?

I'm marking this issue as closed for the time being. If you could provide more information through the `ISSUE_TEMPLATE`, I'd gladly reopen it.

**Comment by seanpdoyle** [comment]
On the surface, this sounds like a misconfiguration of your Devise redirection after an unauthenticated request.

If you could share the contents of your routes file, it might be more apparent what the issue is.
