### ISSUE TITLE
Rails 5.1.0 removed "render text: ..."

### ISSUE THREAD

**Issue by d-schloss-mvg** [thoughtbot/ember-cli-rails#527]
**Which version of [`ruby`](https://www.ruby-lang.org/) is the project developed on?**
ruby-2.2.3

**What is the [`rails`](https://github.com/rails/rails) version?**
5.1.0

**What is the [`ember-cli-rails`](https://github.com/thoughtbot/ember-cli-rails) version (from `Gemfile`)?**
0.8.4

**What is the [`ember-cli-rails-addon`](https://github.com/rondale-sc/ember-cli-rails-addon/) version (from `package.json`)?**
~> 0.8.0 resolved to 0.8.0

**What are the contents of the Rails' view that renders the Ember application?**
Default

**How are the EmberCLI-related routes defined?**
via `mount_ember_app`.

Running a (empty/default) ember-cli-rails project yields the error:
```
You invoked render but did not give any of :partial, :template, :inline, :file, :plain, :html or :body option.
```
referencing this line:
https://github.com/thoughtbot/ember-cli-rails/blob/v0.8.4/app/helpers/ember_rails_helper.rb#L11

According to Rails CHANGELOG this was removed in 5.1.0:
https://github.com/rails/rails/blob/v5.1.0.rc1/actionpack/CHANGELOG.md
"Remove deprecated support to :text in render."

The new way would be `:plain` instead of `:text`. (Which exists since Rails 4.1 ? I am not sure about this though...) as discussed here:
http://stackoverflow.com/questions/43428991/what-to-use-instead-of-render-text-in-rails-5-1-and-later

**Comment by seanpdoyle** [comment]
Fixed by [0.8.5](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.8.5).
