### ISSUE TITLE
 NameError: uninitialized constant Devise

### ISSUE THREAD

**Issue by AsadJamil1** [thoughtbot/ember-cli-rails#528]
I`m using Ruby on rails on Ubuntu for my development and this is the error I`m facing when i try to deploy my app on heroku. using the push command
$ git push heroku master
This outputs :

Counting objects: 1023, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (930/930), done.
Writing objects: 100% (1023/1023), 3.56 MiB | 11.00 KiB/s, done.
Total 1023 (delta 31), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.3.4
remote: -----> Installing dependencies using bundler 1.13.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
**remote:        Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install** bundler`.
remote:        Fetching gem metadata from https://rubygems.org/..........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/.
remote:        Installing i18n 0.8.1
remote:        Installing rake 12.0.0
remote:        Installing json 1.8.6 with native extensions
remote:        Installing minitest 5.10.1
remote:        Installing thread_safe 0.3.6
remote:        Installing builder 3.2.3
remote:        Installing erubis 2.7.0
remote:        Installing mini_portile2 2.1.0
remote:        Installing rack 1.6.5
remote:        Installing arel 6.0.4
remote:        Installing mime-types-data 3.2016.0521
remote:        Installing coffee-script-source 1.12.2
remote:        Installing execjs 2.7.0
remote:        Installing concurrent-ruby 1.0.5
remote:        Installing thor 0.19.4
remote:        Installing multi_json 1.12.1
remote:        Using bundler 1.13.7
remote:        Installing pg 0.20.0 with native extensions
remote:        Installing rails_serve_static_assets 0.0.5
remote:        Installing rails_stdout_logging 0.0.5
remote:        Installing rdoc 4.3.0
remote:        Installing sass 3.4.23
remote:        Installing tilt 2.0.7
remote:        Installing turbolinks-source 5.0.3
remote:        Installing tzinfo 1.2.3
remote:        Installing nokogiri 1.7.1 with native extensions
remote:        Installing rack-test 0.6.3
remote:        Installing mime-types 3.1
remote:        Installing uglifier 3.2.0
remote:        Installing coffee-script 2.4.1
remote:        Installing sprockets 3.7.1
remote:        Installing rails_12factor 0.0.3
remote:        Installing turbolinks 5.0.1
remote:        Installing mail 2.6.5
remote:        Installing loofah 2.0.3
remote:        Installing rails-html-sanitizer 1.0.3
remote:        Installing sdoc 0.4.2
remote:        Installing activesupport 4.2.0
remote:        Installing globalid 0.4.0
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing activemodel 4.2.0
remote:        Installing jbuilder 2.6.3
remote:        Installing activejob 4.2.0
remote:        Installing rails-dom-testing 1.0.8
remote:        Installing actionview 4.2.0
remote:        Installing activerecord 4.2.0
remote:        Installing actionpack 4.2.0
remote:        Installing actionmailer 4.2.0
remote:        Installing sprockets-rails 3.2.0
remote:        Installing railties 4.2.0
remote:        Installing coffee-rails 4.1.1
remote:        Installing sass-rails 5.0.6
remote:        Installing jquery-rails 4.3.1
remote:        Installing rails 4.2.0
remote:        Bundle complete! 15 Gemfile dependencies, 54 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (21.84s)
remote:        Cleaning up the bundler cache.
remote:        Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
**remote: -----> Installing node-v6.10.0-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        NameError: uninitialized constant Devise
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/config/initializers/devise.rb:3:in `<top (required)>'**
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_36d752abc082d93e1fd0e065635a5768/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
**remote:  !     Precompiling assets failed.**
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to floating-mesa-85213.
remote: 
To https://git.heroku.com/floating-mesa-85213.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/floating-mesa-85213.git'

**Comment by seanpdoyle** [comment]
Thanks for opening this issue.

Could you please provide more information by using the [ISSUE_TEMPLATE](https://github.com/thoughtbot/ember-cli-rails/blob/master/.github/ISSUE_TEMPLATE.md)?

I'm marking this issue as closed for the time being. If you could provide more information through the `ISSUE_TEMPLATE`, I'd gladly reopen it.
