### ISSUE TITLE
Make `bower install` step optional for ember:install

### ISSUE THREAD

**Issue by jakeonfire** [thoughtbot/ember-cli-rails#531]
We no longer have any bower dependencies, and yet to use ember-cli-rails we still have a dependency on the bower executable being present (and an empty `bower.json` for that matter). I imagine more ember apps might reach this state as bower itself is kind of being deprecated - the yarn/npm install of bower yields the following post-install message:
```
warning bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
```
I imagine doing `if paths.bower` might be a bit risky as in the opposite case (`bower.json` present but no `bower` installed) there would be no warning. But a means of opting out of the `bower prune && bower install` part would be great, and probably only more in-demand as time goes on.

Idea: if there is no `bower.json` do not do `bower install`...?

**Comment by seanpdoyle** [comment]
In light of https://github.com/thoughtbot/ember-cli-rails/pull/532#issuecomment-308141408, I've reopened this issue.

@jakeonfire could you pull down [`0.8.6`](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.8.6), try it out, and let me know if it resolves your original issue?

We're going to publish `0.8.7`, which reverts this change, then make another, more robust attempt at resolving the issue, which we'll publish as `0.9.0`.

**Comment by brandhuge** [comment]
Please How can I resolve this in Ubuntu 14.04
# npm install -g bower
npm http GET https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/bower
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
/root/bin/bower -> /root/lib/node_modules/bower/bin/bower
bower@1.8.0 /root/lib/node_modules/bower

**Comment by seanpdoyle** [comment]
@jakeonfire could you try to replicate your issue with the current master build?

```rb
# Gemfile
gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails", branch: "master"
```

**Comment by jukeboxhero** [comment]
Ran into this when trying to remove bower from a project- It looks like `ember:install` returns an exit code 1 when `bower.json` is not present, even though it appears to succeed.

```
> bin/rake RAILS_ENV=staging RAILS_GROUPS=assets ember:install

ember-cli: 2.8.0
node: 6.10.0
os: linux x64
yarn install v1.6.0
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.41s.

> echo $?
=> 1

```

This is causing capistrano to fail at this step.  If I add a `bower.json` file with blank dependencies to my project, everything works as expected (minus bower being run).  

Not a blocker, but it would be nice to get rid of that `bower.json` file for good 😄

**Comment by jakeonfire** [comment]
sorry i wasn't able to help earlier. glad it worked out!
