### ISSUE TITLE
yarn support for heroku deploys

### ISSUE THREAD

**Issue by adambedford** [thoughtbot/ember-cli-rails#538]
If I'm reading the deploy output correctly and understanding `heroku_install.sh`, yarn isn't being used in the heroku deployment process.

Is there particular reason for this? It appears that Yarn is supported via the Node buildpack as of December 2016 (https://devcenter.heroku.com/changelog-items/1065)

Seems like this might be as simple as replacing `npm install` with `yarn install`?

**Comment by seanpdoyle** [comment]
Have you tried setting [`yarn: true` in your initializer](https://github.com/thoughtbot/ember-cli-rails/tree/2b52a22fc500d8dd83c7051c26593ca8520fc315#setup)?

```rb
EmberCli.configure do |c|
  c.app :frontend, yarn: true
end
```

**Comment by seanpdoyle** [comment]
I see what you mean. From the [`heroku_install.sh` generator](https://github.com/thoughtbot/ember-cli-rails/blob/2b52a22fc500d8dd83c7051c26593ca8520fc315/lib/generators/ember/heroku/templates/bin_heroku_install.erb#L9):

```erb
for app in <%= app_paths.map { |app_path| %{"#{app_path}"} }.join(" ") -%>; do
  cd $app &&
    npm install &&
    $bower install &&
    cd -
done
```

In the short term, could you try manually replacing the `npm install` with a `yarn install`?

Thanks for bringing this to our attention.

**Comment by kbbpartners** [comment]
This works, but we needed to put an empty `yarn.lock` file in the Rails app root directory to trigger Heroku to use Yarn instead of npm. Maybe someone knows of a better way to force Heroku to use Yarn?

**Comment by seanpdoyle** [comment]
@kbbpartners under what circumstances would you want to use `yarn` without first running `yarn install` locally to generate the `yarn.lock` file?

**Comment by kbbpartners** [comment]
We need yarn to build the ember apps, which are in subdirectories of the Rails app's root. Without a `yarn.lock` in the Rails app's root directory, Heroku chooses npm and then complains that it can't find yarn when it goes to build the Ember apps. So, we end up with a separate `yarn.lock` in the Rails root, and in the root of each Ember app. The `yarn.lock` in the Rails root is empty—just a placeholder to force Heroku to choose yarn over npm.

**Comment by seanpdoyle** [comment]
@adambedford @kbbpartners I've opened https://github.com/thoughtbot/ember-cli-rails/pull/540.

Could you test that out?

```rb
# Gemfile
gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails", branch: "generate-yarn-lock"
```
