### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Samsinite** [thoughtbot/ember-cli-rails#586]
Hi, was wondering if it would be possible to cut a new release, there are a few bugfixes we are using that have been merged into master, and would love get it off of a using an internal release with the latest changes in one of the apps I work on. Thanks!

**Comment by seanpdoyle** [comment]
I've cut a new release: https://rubygems.org/gems/ember-cli-rails/versions/0.11.0.

**Comment by Samsinite** [comment]
Thanks!
