### ISSUE TITLE
No ember-cli-rails-addon v0.11.0

### ISSUE THREAD

**Issue by olbrich** [thoughtbot/ember-cli-rails#589]
The installation instructions...
https://github.com/thoughtbot/ember-cli-rails/blob/1e56a03fb8437f52dfd450454c71cffda2981d66/README.md#L100-L101

Indicate that the 'ember-cli-rails-addon' should match the release version of the gem, however, no new version was published for ember-cli-rails v0.11.0

Please either update the documentation or publish a new npm package (even if it is fundamentally the same with only version number changes).

**Comment by seanpdoyle** [comment]
[Version 0.11.0](https://www.npmjs.com/package/ember-cli-rails-addon/v/0.11.0) has been published to npm.
