### ISSUE TITLE
Support Ruby 3.1, Rails 7.0, and Ember 4.x

### ISSUE THREAD

**Issue by tricknotes** [thoughtbot/ember-cli-rails#594]
I want to update Ruby / Rails / Ember.js in my project which uses ember-cli-rails.
However, all released versions of ember-cli-rails don't support the latest versions of them.

I suggest the following release plan:

1. Firsrt, release current main branch as a minor version as 0.12.0
    - Rails 7 and Ruby 3.1 works fine on this version.
    - Released 🚀 https://github.com/thoughtbot/ember-cli-rails/tree/v0.12.0
2. Then, release dependent libs [ember-cli-rails-addon](https://github.com/rondale-sc/ember-cli-rails-addon) and [ember-cli-rails-assets](https://github.com/seanpdoyle/ember-cli-rails-assets).
    - ember-cli-rails-addon is ready to release. Its master branch works with Ember 4.2.
        - https://github.com/rondale-sc/ember-cli-rails-addon/issues/42
    - ember-cli-rails-assets has some PRs for Ember 4.2.
        - https://github.com/seanpdoyle/ember-cli-rails-assets/pull/14
        - https://github.com/seanpdoyle/ember-cli-rails-assets/pull/15
        - https://github.com/seanpdoyle/ember-cli-rails-assets/pull/16
        - Released 🚀 https://github.com/seanpdoyle/ember-cli-rails-assets/issues/17
    - When these libs are released, Ember 4.2 will work fine on ember-cli-rails without using any hacks.
3. And, drop ember-cli-rails-assets from dependency and make it optional feature.
    - Because it says deprecated in its [README](https://github.com/seanpdoyle/ember-cli-rails-assets#readme).
4. Finally, release ember-cli-rails as 1.0.0. (or 0.13.0)
    - This version supports the latest version of Ruby / Rails / Ember.

How do you think about this idea, all maintainers?
- ember-cli-rails @seanpdoyle
- ember-cli-rails-addon @rwjblue @rondale-sc 
- ember-cli-rails-assets @seanpdoyle 

I'd like to help anything.

----

Related issues:
- https://github.com/thoughtbot/ember-cli-rails/issues/593
- https://github.com/thoughtbot/ember-cli-rails/issues/589

**Comment by seanpdoyle** [comment]
[Version 0.12.0](https://www.npmjs.com/package/ember-cli-rails-addon/v/0.12.0) of the add-on has been released to npm. @tricknotes is that the final blocker for resolving this issue?

**Comment by tricknotes** [comment]
Thanks, @seanpdoyle 
Yes, currently there are no any blockers here :+1:
