### ISSUE TITLE
Watch command called incorrectly

### ISSUE THREAD

**Issue by stewsnooze** [thoughtbot/ember-cli-rails#93]
In ember-cli-rails/lib/ember-cli/app.rb

The watch argument needs 1 passing to it to make it work properly.  Also it would be great to be able to configure what watcher is used (--watcher) as developing with this inside a VM using vagrant won't work with default watchers and the polling watcher is needed.

````
def command(options={})
     watch = options[:watch] ? "--watch" : ""
     "#{ember_path} build #{watch} --environment #{environment} --output-path #{dist_path} #{log_pipe}"
end
````

**Comment by rwz** [comment]
> watch argument needs 1 passing to it to make it work properly

How do you mean?

Ember CLI docs don't mention any arguments to `--watch` and it works fine for us on multiple projects.

We could include `watcher` to make watcher configurable. Care to send a PR?

**Comment by rwz** [comment]
Closing this for now. Feel free to post any updates, we can re-open it later.

**Comment by ryanere** [comment]
@rwz Is there any chance of `watcher` support in the future? I'm running into this same issue.

**Comment by rwz** [comment]
@ryanere what are you talking about? watcher support is build into ember-cli.

**Comment by ryanere** [comment]
I was referring to configuring `watcher` to polling

**Comment by rwz** [comment]
I've never heard of that. How do you do that? In my case ember-cli just picks up watcher by default if it's installed in the system.

**Comment by ryanere** [comment]
I *think* you can pass a watcher flag into `build` as [seen here](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/build.js#L15)? It seems similar to `ember serve --watcher=polling`?  I could be crazy though.

**Comment by rondale-sc** [comment]
@ryanere @stewsnooze You are correct that is a valid option to configure your server to not use fsevents.  We currently do not have a way to set this option.  If you'd like it you could submit a patch that updates https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb#L200 to optionally include this line in the same way we optionally include the watch command.  Though, I believe using the polling watching consumes a considerable amount of cpu (upwards of 20%) for the entire time it is running.

**Comment by stewsnooze** [comment]
https://github.com/rwz/ember-cli-rails/pull/154

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

@rondale-sc @rwz has there been any progress on this?

Thanks for your patience.
