### ISSUE TITLE
Assertion Failed: Path does not start with the provided rootURL

### ISSUE THREAD

**Issue by MichaelVdheeren** [thoughtbot/ember-cli-rails#95]
When runing tests via ember-cli-rails combined with a rootURL and baseURL set in the environment and router, it results in the following error:

```Error: Assertion Failed: Path /tests/inspiration does not start with the provided rootURL /ig/```

environment baseURL: '/ig/'
router rootURL: '/ig/'
tests mounted at '/tests/', application name: 'inspiration'

**Comment by rwz** [comment]
That doesn't seem like a EmberCLI Rails specific problem, does it?

**Comment by thewatts** [comment]
I'm actually having this same issue.

`Error: Assertion Failed: Path /ember-tests/dashboard does not start with the provided rootURL /dashboard/`

My router's `rootURL` is set to `/dashboard/`:
```js
// dashboard/app/router.js 
var Router = Ember.Router.extend({
  location: config.locationType,
  rootURL: '/dashboard/', // technically, I'm setting this is set via the environment.js file (but being explicit here)
});
```

Because the browser based test-runner is mounted to `ember-tests` via the `EmberCLI::Engine`, it seems to be running the tests scoped to that same url, ex: `localhost:3000/ember-tests/dashboard`, when the Ember app itself expects the dashboard to be mounted at `localhost:3000/dashboard`.

**Comment by rondale-sc** [comment]
@rwz @seanpdoyle Is this something we should examine more closely in light of @thewatts info?

**Comment by rwz** [comment]
I don't really use qunit yet, so it's hard for me to say what the problem might be.

**Comment by thewatts** [comment]
@rwz - what are you using to run your tests, `phantomjs` ?

**Comment by rwz** [comment]
@thewatts I don't write tests in javascript. I mostly write integration tests in cucumber/capybara.

**Comment by thewatts** [comment]
ahh, okay.

capybara has bit me pretty hard in the past with javascript tests - so I'm striving to use the provided javascript testing suites :)

**Comment by ryanere** [comment]
This an issue for me as well.  Also, is the environment being set to 'test' when the tests are run from the EmberCLI engine?

**Comment by MichaelVdheeren** [comment]
@ryanere I believe it is not :-(

**Comment by cemarte** [comment]
Hi all,

Same problem here. Testing with ember-cli 0.2.3 default "qunit": "~1.17.1"+ "phantomjs": "1.9.15".

My rootURL is /admin/.

Running ember test --server or ember serve and accessind localhost:4200/tests throws the following error:

```
Error: Assertion Failed: Path /6729/tests/index.html does not start with the provided rootURL /admin/
```


Any ideas?

**Comment by a6ftcruton** [comment]
same issue here:
`Error: Assertion Failed: Path /tests does not start with the provided rootURL /dashboard`

**Comment by timkellogg** [comment]
Same issue.

**Comment by seanpdoyle** [comment]
@drapergeek does this describe the issues you were seeing early on in your latest EmberCLI-Rails project?

**Comment by drapergeek** [comment]
>@drapergeek does this describe the issues you were seeing early on in your latest EmberCLI-Rails project?

I think this is a different issue, sorry I couldn't be more helpful in this case.

**Comment by seanpdoyle** [comment]
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.
