### ISSUE TITLE
<base href="/foo"> not included in view helpers

### ISSUE THREAD

**Issue by seanpdoyle** [thoughtbot/ember-cli-rails#98]
Currently, the value of `baseURL` isn't exposed through the Rails view helpers.

In my case, the `baseURL` is `/admin/editor`

To work around this, I manually embedded:

```erb
<base href="/admin/editor">
```

In my `app/views/ember/index.html.erb`.

I don't think it would be possible to extract the value from the Rails side of things, so we might want to mention this as a gotcha that requires manual intervention?

@rwz @rondale-sc your thoughts?

**Comment by rwz** [comment]
Where does it usually come from in an pure EmberCLI app?

**Comment by seanpdoyle** [comment]
`{{content-for 'head'}}` or `{{content-for 'head-footer'}}` maybe?

**Comment by rwz** [comment]
Yeah, but where do you specify what values goes?

**Comment by seanpdoyle** [comment]
https://github.com/ember-cli/ember-cli/blob/18d377b264859548f41aba6c3ea2015b90978068/blueprints/app/files/config/environment.js#L7

**Comment by rwz** [comment]
Well, ¯\\\_(ツ)_/¯ 

You're right, probably the best way is to mention it in the README.

**Comment by rondale-sc** [comment]
Yeah, I think just mentioning it in the readme should be enough.  It would probably be possible to have ember-cli-rails-addon put that information somewhere that Rails coould see it though it would probably involve writing a file and having ember-cli-rails read it in which is probably not a good idea.  

I suspect that writing the tag manually would suffice and mentioning in the readme.   Alternatively, we now send the environment from the rails process through to the child process (in this case the ember build process) so maybe it'd be possible to have it read in from the environment that way.

For example we could write the environment var and just set it with .dotenv.  Not sure how practical that is as compared to your solution.

**Comment by voldy** [comment]
I would love to see it in the readme.

**Comment by rwz** [comment]
@voldy pull requests are welcome.

**Comment by seanpdoyle** [comment]
@rondale-sc this might be addressed by the approach we've discussed this morning.

Either way, it looks like https://github.com/ember-cli/ember-cli/issues/2633 will remove the `<base>` tag, so I'm closing this for now.
